import {
  defineRenderShape,
  defineRenderShapeCatalog,
} from '@renderer/rendering/evidence/defineRenderShape'

// Claude render-shape catalog (Phase 4, PR #555).
//
// SEEDED from the 48-bundle frozen corpus (26 claude bundles) via
// scripts/audit-rendering-shapes.mts --seed on 2026-07-16 — every entry is
// an OBSERVED wire structure, none is invented from a tool list (the Phase
// 4 gate). Grouping: one id per (plane family × tool/discriminator);
// structural variants of the same semantics share the id as extra
// fingerprints, per the plan's "multiple fingerprints under one shape id"
// rule. Split an entry only when the VISUAL interpretation or lifecycle
// genuinely differs.
//
// Every disposition is now an enforceable Phase 10 promise. Where a stable
// structural envelope legitimately routes by bounded content (Git vs an
// ordinary Bash command, or an empty vs non-empty continuation), the catalog
// lists that finite alternate explicitly. `planned` remains an authoring
// vocabulary in the type system, but shipping catalog entries may not use it.
//
// fixtures.final reference the bundle corpus (`rendering-bundles/<file>`)
// as seed evidence; dedicated shape fixtures under
// testing/fixtures/rendering-shapes/ join them as capture soaks + the
// extract script produce redacted minimal cases.
//
// TODO(condition-shape-soak): the provider can emit six normalized live
// condition kinds, but the retained corpus predates condition-plane capture.
// Do not fingerprint TypeScript examples and call them evidence. The first
// real developer recording of each kind must arrive through the Unknown Shape
// Inbox, then land here with its exact destination disposition and fixture.
export const CLAUDE_RENDER_SHAPES = defineRenderShapeCatalog('claude', {
  'claude.entry.attachment.v1': defineRenderShape({
    id: 'claude.entry.attachment.v1',
    provider: 'claude',
    fingerprints: ["fp2-17325b53","fp2-1f43958e","fp2-20f22b8f","fp2-38e7ef3d","fp2-3ae4cf2b","fp2-40425c51","fp2-43858260","fp2-4d79e5d3","fp2-581ac6d5","fp2-60e3d224","fp2-6399aefe","fp2-69882ce4","fp2-753c33b9","fp2-83a3fbfd","fp2-8628c635","fp2-8feef6e3","fp2-abe64889","fp2-b0d9d248","fp2-b4071732","fp2-b8a64f27","fp2-bc298de8","fp2-c1d8a2a6","fp2-cdb2f73a","fp2-d192dbac","fp2-dd5cff49","fp2-e4e63295","fp2-f08b1406","fp2-f30522fc","fp2-f7b66ff2"],
    eventTypes: ["attachment"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Hook and provider attachment records are intentionally excluded by the feed ownership ledger; if admitted by another transcript surface, the bounded muted system fallback remains total.' },
    why: 'Phase 8 classifies the 121 observed attachment variants as diagnostic transcript metadata, not conversation. TODO(system-attachment-grammar): promote a specific hook/provider notice only after a fixture proves it belongs in the user-facing feed rather than the debug transcript.',
  }),
  'claude.entry.pr-link.v1': defineRenderShape({
    id: 'claude.entry.pr-link.v1',
    provider: 'claude',
    fingerprints: ["fp2-696bfb91"],
    eventTypes: ["pr-link"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json","rendering-bundles/2026-06-14T14-02-05-796-a8ad1ebb.json","rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'PR-link records are repeated session metadata and remain outside the conversational ledger; the muted system fallback is available if a future product surface admits them.' },
    why: 'Phase 8 deliberately avoids painting 157 repeated PR metadata records into the feed. TODO(pr-link-product-surface): add a deduplicated session-level affordance only after its owner and replay contract are specified.',
  }),
  'claude.entry.queue-operation.v1': defineRenderShape({
    id: 'claude.entry.queue-operation.v1',
    provider: 'claude',
    fingerprints: ["fp2-93af4392","fp2-ffa1daf8"],
    eventTypes: ["queue-operation"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T14-02-05-796-a8ad1ebb.json","rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json","rendering-bundles/2026-06-14T14-32-42-750-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Queue-operation records are consumed by queue reconstruction and excluded from feed rows; a generic system row remains the safe transcript fallback.' },
    why: 'Phase 8 records the intentional non-feed owner: Claude queue reconstruction consumes enqueue/dequeue metadata, while the queue lane owns the user-visible state. Painting the durable bookkeeping as chat would duplicate queued prompts.',
  }),
  'claude.entry.system-compact-boundary.v1': defineRenderShape({
    id: 'claude.entry.system-compact-boundary.v1',
    provider: 'claude',
    fingerprints: ["fp2-d3594ad3"],
    eventTypes: ["system:compact_boundary"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-22T12-46-15-717-c973322e.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'shared.compaction', protocolId: 'compaction.boundary' },
    why: 'GRADUATED Phase 10: Claude durable-entry dispatch now owns boundary recognition and delegates only the provider-neutral visual grammar to shared.compaction. The durable transcript entry, not a transient screen condition, is the replay source of truth.',
  }),
  'claude.entry.system-turn-duration.v1': defineRenderShape({
    id: 'claude.entry.system-turn-duration.v1',
    provider: 'claude',
    fingerprints: ["fp2-2c0c0341","fp2-624904d3","fp2-acba5abf","fp2-cb7091d5"],
    eventTypes: ["system:turn_duration"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Turn-duration records are diagnostic metadata excluded by the ownership ledger; if surfaced in diagnostics they use the bounded muted system fallback.' },
    why: 'Phase 8 explicitly classifies turn_duration as non-conversational telemetry. A dedicated feed component would add one noisy row per turn without providing an action or durable semantic artifact.',
  }),
  'claude.entry.compact-summary.v1': defineRenderShape({
    id: 'claude.entry.compact-summary.v1',
    provider: 'claude',
    fingerprints: ["fp2-92c29c6f"],
    eventTypes: ["user"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-21T19-19-55-972-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'shared.compaction', protocolId: 'compaction.summary' },
    why: 'Claude marks the synthetic user entry with isCompactSummary. Provider durable-entry dispatch owns that admission and delegates only the provider-neutral summary grammar to shared.compaction, so replay survives without screen state.',
  }),
  'claude.entry.task-notification.v1': defineRenderShape({
    id: 'claude.entry.task-notification.v1',
    provider: 'claude',
    fingerprints: ["fp2-688dff42"],
    eventTypes: ["user"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-bundles/2026-06-21T20-14-23-131-62432945.json","rendering-bundles/2026-06-22T12-34-16-431-2db014bc.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.task-notification' },
    why: 'The XML carrier is a Claude protocol artifact, not user conversation and not a generic subagent result. Claude admission prevents the shell or Codex from inheriting this provider-specific completion contract.',
  }),
  'claude.semantic.agent.v1': defineRenderShape({
    id: 'claude.semantic.agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-279fd9c3","fp2-7148ba15","fp2-d06574fa","fp2-d36d2d0d"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: parsed semantic Agent input now routes through the same provider adapter/card as the committed operation; incomplete prefixes keep the visible generic stream until the strict Agent grammar closes.',
  }),
  'claude.semantic.askuserquestion.v1': defineRenderShape({
    id: 'claude.semantic.askuserquestion.v1',
    provider: 'claude',
    fingerprints: ["fp2-21c00403","fp2-af6fbebc"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-17T11-50-56-053-a6c70f19.json","rendering-bundles/2026-06-21T18-16-49-177-fc397785.json","rendering-bundles/2026-06-21T19-19-55-972-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'GRADUATED Phase 8: complete semantic question input is admitted by Claude dispatch and rendered by the existing condition-gated SessionFeed interaction surface; the shared feed no longer routes by tool name.',
  }),
  'claude.semantic.bash.v1': defineRenderShape({
    id: 'claude.semantic.bash.v1',
    provider: 'claude',
    fingerprints: ["fp2-326d9120","fp2-42e564e8","fp2-9d6cf8fc","fp2-cad93e7b","fp2-ee539da9","fp2-f0bd83a7"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    alternateDispositions: [
      { kind: 'specialized', rendererId: 'shared.command', protocolId: 'command.git' },
    ],
    why: 'GRADUATED Phase 10: Claude semantic dispatch owns every Bash prefix and complete input. Ordinary/partial commands use the Claude row; evidence-backed Git commands use the shared command formatter through the provider adapter, with the exact protocol carried by the receipt.',
  }),
  'claude.semantic.edit.v1': defineRenderShape({
    id: 'claude.semantic.edit.v1',
    provider: 'claude',
    fingerprints: ["fp2-2323238a","fp2-28bc3225","fp2-c29bd417","fp2-d152c062"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T14-02-05-796-a8ad1ebb.json","rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-29T11-38-28-652-42071335.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'A prefix without a closed file path remains visible through the bounded structured fallback.' } },
    alternateDispositionsByLifecycle: { prefix: [{ kind: 'specialized', rendererId: 'claude.rows.dispatch' }] },
    why: 'GRADUATED Phase 10: complete Edit input is provider-owned; a prefix earns that card only after file_path closes. The finite prefix routes describe that content threshold without pretending the structural fingerprint alone resolves it.',
  }),
  'claude.semantic.enterworktree.v1': defineRenderShape({
    id: 'claude.semantic.enterworktree.v1',
    provider: 'claude',
    fingerprints: ["fp2-48eed2e4"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-29T11-38-28-652-42071335.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'One invocation without a paired transition/result does not prove a workspace lifecycle grammar; bounded structured input is the truthful representation.' },
    why: 'Phase 8 leaves EnterWorktree on the total generic path. TODO(worktree-transition-evidence): graduate only after paired success, failure, and replay fixtures establish the actual before/after state rather than inferring it from the verb.',
  }),
  'claude.semantic.mcp-orchestration-close-agent.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-close-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-4789512c","fp2-a13b27bf","fp2-ecd79fdb"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-bundles/2026-06-29T14-11-47-099-1b2b5e96.json","rendering-bundles/2026-06-29T14-13-09-044-1b2b5e96.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: the exact mcp__agent_code__ namespace proves the source-controlled orchestration protocol; new 2026-07-17 prefix variants remain visible until parsed input is complete.',
  }),
  'claude.semantic.mcp-orchestration-close-run.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-close-run.v1',
    provider: 'claude',
    fingerprints: ["fp2-782d249b","fp2-b0effe07"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/agent-code-orchestration/final.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7 from the live capture plus the owned close-run schema; the curated fixture records that provenance because the frozen bundle corpus did not contain this semantic mirror.',
  }),
  'claude.semantic.mcp-orchestration-create-agent.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-create-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-23af1de7","fp2-78b9c8e2","fp2-7b34fd2f","fp2-7b63e36c","fp2-7ed23c16","fp2-e64f1cc9","fp2-eebdcf03"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-21T19-19-55-972-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: Agent Code create is provider-recognized by its exact MCP namespace and rendered by the shared owned-protocol view, never by the open-world MCP fallback.',
  }),
  'claude.semantic.mcp-orchestration-list-agents.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-list-agents.v1',
    provider: 'claude',
    fingerprints: ["fp2-74655986","fp2-a8b077ae","fp2-f0d1e7da"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-21T20-14-23-131-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: list-agent inputs share the owned protocol card; the newly observed prefix stays generic until the reducer provides authoritative parsed input.',
  }),
  'claude.semantic.mcp-orchestration-read-agent.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-read-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-cb2cb220"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: read-agent is an owned orchestration discovery operation, with bounded per-message disclosures and an exact raw protocol fallback inside the card.',
  }),
  'claude.semantic.mcp-orchestration-send-prompt.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-send-prompt.v1',
    provider: 'claude',
    fingerprints: ["fp2-0538cebb","fp2-c9fd7a40"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: send-prompt input is provider-owned only for the agent_code namespace; failures keep operation-specific diagnostics in the raw protocol disclosure.',
  }),
  'claude.semantic.mcp-orchestration-wait-agents.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-wait-agents.v1',
    provider: 'claude',
    fingerprints: ["fp2-0ce1d5ee","fp2-0fa4ac05","fp2-93dec72c","fp2-cb45a301"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-21T20-14-23-131-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: wait results render bounded agent summaries and lazy child output; the 2026-07-17 complete-input variant is folded into the same visual operation.',
  }),
  'claude.semantic.notebookedit.v1': defineRenderShape({
    id: 'claude.semantic.notebookedit.v1',
    provider: 'claude',
    fingerprints: ["fp2-974fdedb","fp2-a64230ba"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Two live input shapes with no durable notebook/result fixture cannot support an honest cell diff; bounded structured input preserves the available evidence.' },
    why: 'Phase 8 intentionally declines a speculative NotebookEdit component. TODO(notebook-edit-evidence): capture notebook path, cell identity/type, edit mode, paired terminal result, and replay before adding a highlighted cell grammar.',
  }),
  'claude.semantic.read.v1': defineRenderShape({
    id: 'claude.semantic.read.v1',
    provider: 'claude',
    fingerprints: ["fp2-3ad02d79","fp2-7e45af3e","fp2-f959f6c0","fp2-faf7aca7"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'GRADUATED Phase 7: complete semantic Read input is converted to the committed ToolUseBlock contract and routed through the same Claude read adapter/component; prefixes remain visible.',
  }),
  'claude.semantic.skill.v1': defineRenderShape({
    id: 'claude.semantic.skill.v1',
    provider: 'claude',
    fingerprints: ["fp2-690826ce","fp2-72e2f303"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'GRADUATED Phase 8: complete Skill input renders through the Claude-owned task activity adapter; the paired launch acknowledgement is absorbed only after its captured grammar validates.',
  }),
  'claude.semantic.taskcreate.v1': defineRenderShape({
    id: 'claude.semantic.taskcreate.v1',
    provider: 'claude',
    fingerprints: ["fp2-0203f177","fp2-072fd53b","fp2-15718172"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-22T09-05-45-698-7733b0fc.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Task identity and descriptions are not complete until all required TaskCreate fields close.' } },
    why: 'GRADUATED Phase 8: complete semantic TaskCreate input shares the committed lifecycle card; incomplete prefixes retain bounded raw evidence.',
  }),
  'claude.semantic.taskupdate.v1': defineRenderShape({
    id: 'claude.semantic.taskupdate.v1',
    provider: 'claude',
    fingerprints: ["fp2-083fb7d8","fp2-3159a259","fp2-37a1ba2a"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'A task id plus a recognized terminal/in-progress status is required before specialization.' } },
    why: 'GRADUATED Phase 8: recognized TaskUpdate statuses now read as lifecycle transitions; drifted statuses remain generic rather than being guessed.',
  }),
  'claude.semantic.text.v1': defineRenderShape({
    id: 'claude.semantic.text.v1',
    provider: 'claude',
    fingerprints: ["fp2-c5003421","fp2-f134003d"],
    eventTypes: ["text"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Live text is provider-neutral prose painted by the shared semantic row after provider dispatch declines non-tool content.' },
    why: 'GRADUATED Phase 9: Claude semantic dispatch intentionally owns only provider tool vocabulary. Text always reaches the shared bounded prose path, so leaving this planned would make a deterministic route invisible to drift auditing.',
  }),
  'claude.semantic.thinking.v1': defineRenderShape({
    id: 'claude.semantic.thinking.v1',
    provider: 'claude',
    fingerprints: ["fp2-a006c766","fp2-e8268b73"],
    eventTypes: ["thinking"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Non-empty thinking is painted by the provider-neutral semantic disclosure.' },
    alternateDispositions: [
      { kind: 'absorbed', ownerRendererId: 'semantic.blockrow', reason: 'Empty or encrypted thinking is represented by the work indicator instead of a blank row.' },
    ],
    why: 'GRADUATED Phase 10 with a finite content split: visible thinking uses the shared disclosure; empty/encrypted thinking is explicitly absorbed by semantic.blockrow. The observer records which route actually occurred.',
  }),
  'claude.semantic.toolsearch.v1': defineRenderShape({
    id: 'claude.semantic.toolsearch.v1',
    provider: 'claude',
    fingerprints: ["fp2-9cf197fc","fp2-c3b66ae8","fp2-ed0e9987"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: parsed semantic ToolSearch reuses the committed structured discovery row and result adapter instead of maintaining a second live JSON grammar.',
  }),
  'claude.semantic.webfetch.v1': defineRenderShape({
    id: 'claude.semantic.webfetch.v1',
    provider: 'claude',
    fingerprints: ["fp2-02b29108","fp2-39f6fc6f"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/web-fetch/semantic-final.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7 from live capture: authoritative parsed input reuses the committed WebFetch adapter; the synthetic fixture preserves the captured structure without inventing a frozen-bundle claim.',
  }),
  'claude.semantic.websearch.v1': defineRenderShape({
    id: 'claude.semantic.websearch.v1',
    provider: 'claude',
    fingerprints: ["fp2-790c707c","fp2-befc9470"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/web-search/semantic-final.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7 from live capture: authoritative parsed input reuses the committed WebSearch adapter; streaming prefixes keep the bounded generic path until the query closes.',
  }),
  'claude.semantic.write.v1': defineRenderShape({
    id: 'claude.semantic.write.v1',
    provider: 'claude',
    fingerprints: ["fp2-80a4cece","fp2-ad91ef51","fp2-bb84f08f"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json","rendering-bundles/2026-06-14T14-32-42-750-a8ad1ebb.json","rendering-bundles/2026-06-14T14-32-54-340-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'A prefix without a closed file path remains visible through the bounded structured fallback.' } },
    alternateDispositionsByLifecycle: { prefix: [{ kind: 'specialized', rendererId: 'claude.rows.dispatch' }] },
    why: 'GRADUATED Phase 10: complete Write input is provider-owned; streaming input earns the partial file card only after the bounded scanner closes file_path. Both legal prefix routes are declared rather than hidden behind a planned wildcard.',
  }),
  'claude.tool-result.tool-result.v1': defineRenderShape({
    id: 'claude.tool-result.tool-result.v1',
    provider: 'claude',
    fingerprints: ["fp2-05148fe5","fp2-5088f736","fp2-ac6ff7c0","fp2-cfd69380"],
    eventTypes: ["tool_result"],
    planes: ["committed-tool-result"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Unknown, uncorrelated, or drifted result envelopes remain visibly formatted by the shared result fallback.' },
    alternateDispositions: [
      { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
      { kind: 'absorbed', ownerRendererId: 'claude.rows.dispatch', reason: 'A validated paired provider card preserves the useful result evidence.' },
      { kind: 'absorbed', ownerRendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration', reason: 'The source-controlled Agent Code orchestration card preserves its validated result protocol.' },
      { kind: 'absorbed', ownerRendererId: 'claude.rows.dispatch', protocolId: 'agent-code.workspace', reason: 'The source-controlled Agent Code workspace card preserves its validated result protocol.' },
      { kind: 'absorbed', ownerRendererId: 'shared.command', protocolId: 'command.git', reason: 'The paired Git operation view preserves the bounded result evidence.' },
    ],
    why: 'GRADUATED Phase 10: the paired operation boundary, not the uniform result envelope, decides ownership. The catalog enumerates the only legal visible/absorbed routes and every absorption names its evidence owner.',
  }),
  'claude.tool-use.agent.v1': defineRenderShape({
    id: 'claude.tool-use.agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-0406b30d","fp2-29d6969a","fp2-76182cb6","fp2-8f84787b"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/agent/final.json","rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Observed across the frozen corpus and fresh 2026-07-16 recordings; Phase 7 moves the built-in Claude Agent grammar off the shared spawn interceptor into a provider-owned paired card.',
  }),
  'claude.tool-use.askuserquestion.v1': defineRenderShape({
    id: 'claude.tool-use.askuserquestion.v1',
    provider: 'claude',
    fingerprints: ["fp2-78de3d3e"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-21T18-16-49-177-fc397785.json","rendering-bundles/2026-06-21T19-19-55-972-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'GRADUATED Phase 8: committed questions and their losslessly-carried answers now render through the Claude provider component, with validated result absorption instead of a central name exception.',
  }),
  'claude.tool-use.bash.v1': defineRenderShape({
    id: 'claude.tool-use.bash.v1',
    provider: 'claude',
    fingerprints: ["fp2-3da1120c","fp2-490f20a2","fp2-c4cd6b80","fp2-cb2c6fd2","fp2-eab9de5c","fp2-fd75288a"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    alternateDispositions: [
      { kind: 'specialized', rendererId: 'shared.command', protocolId: 'command.git' },
    ],
    why: 'GRADUATED Phase 10: Claude operation dispatch owns Bash and chooses either its normal command row or the evidence-backed Git formatter. No central feed interception remains, and both routes carry exact receipts.',
  }),
  'claude.tool-use.edit.v1': defineRenderShape({
    id: 'claude.tool-use.edit.v1',
    provider: 'claude',
    fingerprints: ["fp2-8bad26f1"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json","rendering-bundles/2026-06-14T14-02-05-796-a8ad1ebb.json","rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (12 sightings); structural variants share this id. GRADUATED 2026-07-16: cut over to the code-edit protocol (adapter + CodeEditView); receipts must name this renderer or the sighting files as misrouted',
  }),
  'claude.tool-use.lsp.v1': defineRenderShape({
    id: 'claude.tool-use.lsp.v1',
    provider: 'claude',
    fingerprints: ["fp2-296283bb"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'A single invocation with no durable paired result cannot establish operation, location, result-count, or failure semantics; the structured fallback preserves every captured field.' },
    why: 'Phase 8 keeps LSP explicit and generic. TODO(lsp-evidence): add a provider component only after paired symbol/file/range, multi-location, empty, and error fixtures prove a stable grammar.',
  }),
  'claude.tool-use.mcp-get-projects-list.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-get-projects-list.v1',
    provider: 'claude',
    fingerprints: ["fp2-51ac2727"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'An open-world MCP server with one invocation-only sighting uses the typed MCP/structured fallback rather than an invented server-specific component.' },
    why: 'Phase 8 classifies get-projects-list through generic MCP hierarchy. TODO(mcp-server-specialization): require repeated paired fixtures demonstrating a visual grammar the typed MCP blocks cannot express.',
  }),
  'claude.tool-use.mcp-list-calendars.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-list-calendars.v1',
    provider: 'claude',
    fingerprints: ["fp2-40794dd0"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'An open-world MCP server with one invocation-only sighting uses the typed MCP/structured fallback rather than an invented server-specific component.' },
    why: 'Phase 8 classifies list-calendars through generic MCP hierarchy. TODO(mcp-server-specialization): require repeated paired fixtures demonstrating a visual grammar the typed MCP blocks cannot express.',
  }),
  'claude.tool-use.mcp-list-labels.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-list-labels.v1',
    provider: 'claude',
    fingerprints: ["fp2-cbe2bb34"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'An open-world MCP server with one invocation-only sighting uses the typed MCP/structured fallback rather than an invented server-specific component.' },
    why: 'Phase 8 classifies list-labels through generic MCP hierarchy. TODO(mcp-server-specialization): require repeated paired fixtures demonstrating a visual grammar the typed MCP blocks cannot express.',
  }),
  'claude.tool-use.mcp-orchestration-close-agent.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-close-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-8d5a374c"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-29T14-11-47-099-1b2b5e96.json","rendering-bundles/2026-06-29T14-13-09-044-1b2b5e96.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: the provider adapter proves the exact agent_code namespace before the owned orchestration close card can claim this committed operation.',
  }),
  'claude.tool-use.mcp-orchestration-close-run.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-close-run.v1',
    provider: 'claude',
    fingerprints: ["fp2-d51238ff"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-21T18-16-49-177-fc397785.json","rendering-bundles/2026-06-21T19-19-55-972-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: close-run uses the source-controlled Agent Code result contract and retains closed/skipped session ids in the raw protocol disclosure.',
  }),
  'claude.tool-use.mcp-orchestration-create-agent.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-create-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-3bb32d92","fp2-89e9a6cc","fp2-b50901e3","fp2-e715b7f7","fp2-f53af93d","fp2-fdc02391"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-21T19-19-55-972-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: committed create-agent bypasses the deleted central name-only spawn route and renders the owned Agent Code lifecycle/result protocol.',
  }),
  'claude.tool-use.mcp-orchestration-list-agents.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-list-agents.v1',
    provider: 'claude',
    fingerprints: ["fp2-5ba767ef","fp2-f4ce844a"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-21T18-16-49-177-fc397785.json","rendering-bundles/2026-06-21T20-14-23-131-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: list results use a capped agent table while the full structured protocol stays available behind a lazy disclosure.',
  }),
  'claude.tool-use.mcp-orchestration-read-agent.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-read-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-37f59a8d","fp2-e6ed123a"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-29T14-11-47-099-1b2b5e96.json","rendering-bundles/2026-06-29T14-13-09-044-1b2b5e96.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: Agent Code output is source-bounded and then DOM-bounded again with per-agent/per-message lazy disclosures; parser drift falls through visibly.',
  }),
  'claude.tool-use.mcp-orchestration-send-prompt.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-send-prompt.v1',
    provider: 'claude',
    fingerprints: ["fp2-4f2b8052"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-29T14-11-47-099-1b2b5e96.json","rendering-bundles/2026-06-29T14-13-09-044-1b2b5e96.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: prompt text is collapsed/lazy, target identity remains visible, and uncertain delivery diagnostics are retained instead of collapsed to success/failure folklore.',
  }),
  'claude.tool-use.mcp-orchestration-wait-agents.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-wait-agents.v1',
    provider: 'claude',
    fingerprints: ["fp2-358c4c4f","fp2-447639d2","fp2-59ede605","fp2-b2fe7f1d"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-21T18-16-49-177-fc397785.json","rendering-bundles/2026-06-21T20-14-23-131-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: wait is an owned multi-agent protocol with capped rows and nested lazy outputs; the 2026-07-17 cap-field variant joins the same visual operation.',
  }),
  'claude.tool-use.mcp-ref-search-documentation.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-ref-search-documentation.v1',
    provider: 'claude',
    fingerprints: ["fp2-12a71d56"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'An open-world MCP server with one invocation-only sighting uses the typed MCP/structured fallback rather than an invented server-specific component.' },
    why: 'Phase 8 classifies documentation search through generic MCP hierarchy. TODO(mcp-server-specialization): require repeated paired fixtures demonstrating a visual grammar the typed MCP blocks cannot express.',
  }),
  'claude.tool-use.monitor.v1': defineRenderShape({
    id: 'claude.tool-use.monitor.v1',
    provider: 'claude',
    fingerprints: ["fp2-3ccd9ea4"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'One Monitor invocation without correlated state/result evidence cannot prove a task lifecycle; bounded structured rendering keeps the operation visible.' },
    why: 'Phase 8 declines to equate Monitor with TaskCreate/TaskUpdate. TODO(monitor-evidence): capture paired running, terminal, failure, and replay states before defining its lifecycle vocabulary.',
  }),
  'claude.tool-use.notebookedit.v1': defineRenderShape({
    id: 'claude.tool-use.notebookedit.v1',
    provider: 'claude',
    fingerprints: ["fp2-cc6cefa5"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'One committed invocation without paired notebook content/result cannot support a trustworthy cell diff; bounded structured input remains visible.' },
    why: 'Phase 8 intentionally keeps committed NotebookEdit generic for the same evidence gap as its semantic form. TODO(notebook-edit-evidence): capture cell identity/type/mode plus success, failure, and replay.',
  }),
  'claude.tool-use.read.v1': defineRenderShape({
    id: 'claude.tool-use.read.v1',
    provider: 'claude',
    fingerprints: ["fp2-17828ea4","fp2-4f808916","fp2-668e025e","fp2-9cdbe334"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/read/final.json","rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Observed in the frozen corpus and live recordings; Phase 7 routes the committed invocation through the provider-owned Read component.',
  }),
  'claude.tool-use.schedulewakeup.v1': defineRenderShape({
    id: 'claude.tool-use.schedulewakeup.v1',
    provider: 'claude',
    fingerprints: ["fp2-bbd55bdc"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-07-07T13-17-20-472-5b19529f.json","rendering-bundles/2026-07-07T13-17-48-452-5b19529f.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'GRADUATED Phase 8: the captured delay/reason/prompt contract renders as a wake lifecycle card with the full prompt behind explicit expansion.',
  }),
  'claude.tool-use.skill.v1': defineRenderShape({
    id: 'claude.tool-use.skill.v1',
    provider: 'claude',
    fingerprints: ["fp2-c651173c"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'GRADUATED Phase 8: committed Skill input and its strict launch acknowledgement share one provider-owned activity row.',
  }),
  'claude.tool-use.taskcreate.v1': defineRenderShape({
    id: 'claude.tool-use.taskcreate.v1',
    provider: 'claude',
    fingerprints: ["fp2-af9ab62f"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-22T09-05-45-698-7733b0fc.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'GRADUATED Phase 8: committed TaskCreate now exposes subject/description/active form as one lifecycle card and preserves exact input on demand.',
  }),
  'claude.tool-use.taskget.v1': defineRenderShape({
    id: 'claude.tool-use.taskget.v1',
    provider: 'claude',
    fingerprints: ["fp2-1c76760b"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'One TaskGet invocation with no paired result cannot prove the returned task schema; the bounded fallback preserves the task id and future fields.' },
    why: 'Phase 8 specializes only captured task mutations. TODO(task-query-evidence): capture current task detail, missing-task, failure, and replay fixtures before adding a query card.',
  }),
  'claude.tool-use.taskoutput.v1': defineRenderShape({
    id: 'claude.tool-use.taskoutput.v1',
    provider: 'claude',
    fingerprints: ["fp2-8232b4d2"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'TaskOutput is not a shell command and one invocation-only sighting does not prove output paging or terminal states; bounded structured rendering is honest.' },
    why: 'Phase 8 corrects the old command-family guess and keeps TaskOutput generic. TODO(task-output-evidence): capture correlated output, empty, running, error, large-output, and replay cases before specialization.',
  }),
  'claude.tool-use.taskstop.v1': defineRenderShape({
    id: 'claude.tool-use.taskstop.v1',
    provider: 'claude',
    fingerprints: ["fp2-8d4dfa22"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'TaskStop is a lifecycle mutation, not a command, and one invocation without a terminal result cannot establish stop semantics; bounded structured rendering is honest.' },
    why: 'Phase 8 corrects the old command-family guess and keeps TaskStop generic. TODO(task-stop-evidence): capture stopped/already-terminal/not-found/failure and replay before adding lifecycle copy.',
  }),
  'claude.tool-use.taskupdate.v1': defineRenderShape({
    id: 'claude.tool-use.taskupdate.v1',
    provider: 'claude',
    fingerprints: ["fp2-ddd6329d"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'GRADUATED Phase 8: committed TaskUpdate displays its task id and proven status while unknown status generations fall through visibly.',
  }),
  'claude.tool-use.toolsearch.v1': defineRenderShape({
    id: 'claude.tool-use.toolsearch.v1',
    provider: 'claude',
    fingerprints: ["fp2-68bade64"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/tool-search/final.json","rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Observed in the frozen corpus and live recordings; Phase 7 routes the committed invocation through the provider-owned ToolSearch component.',
  }),
  'claude.tool-use.webfetch.v1': defineRenderShape({
    id: 'claude.tool-use.webfetch.v1',
    provider: 'claude',
    fingerprints: ["fp2-9382b7f6"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/web-fetch/final.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Observed in fresh 2026-07-16 recordings; Phase 7 routes committed WebFetch invocation and paired string output through provider-owned components.',
  }),
  'claude.tool-use.websearch.v1': defineRenderShape({
    id: 'claude.tool-use.websearch.v1',
    provider: 'claude',
    fingerprints: ["fp2-c5a5c976"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/web-search/final.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Observed in fresh 2026-07-16 recordings; Phase 7 routes committed WebSearch invocation and paired string output through provider-owned components.',
  }),
  'claude.tool-use.write.v1': defineRenderShape({
    id: 'claude.tool-use.write.v1',
    provider: 'claude',
    fingerprints: ["fp2-471cb5b5"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json","rendering-bundles/2026-06-14T14-32-42-750-a8ad1ebb.json","rendering-bundles/2026-06-14T14-32-54-340-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (16 sightings); structural variants share this id. GRADUATED 2026-07-16: cut over to the code-edit protocol (adapter + CodeEditView); receipts must name this renderer or the sighting files as misrouted',
  }),})

export type ClaudeRenderShapeId = keyof typeof CLAUDE_RENDER_SHAPES
