import {
  defineRenderShape,
  defineRenderShapeCatalog,
} from '@renderer/rendering/evidence/defineRenderShape'

// Claude render-shape catalog (Phase 4, PR #555).
//
// SEEDED from the 48-bundle frozen corpus (26 claude bundles) via
// scripts/audit-rendering-shapes.mts --seed on 2026-07-16 — every entry is
// an OBSERVED wire structure, none is invented from a tool list (the Phase
// 4 gate). Grouping: one id per (plane family × tool/discriminator);
// structural variants of the same semantics share the id as extra
// fingerprints, per the plan's "multiple fingerprints under one shape id"
// rule. Split an entry only when the VISUAL interpretation or lifecycle
// genuinely differs.
//
// All dispositions start `planned`: the legacy painter routes by CONTENT
// (git Bash → widget, other Bash → generic), which a structural catalog
// must tolerate until Phase 5+ receipts land — see
// catalogCoverage.outcomeSatisfiesDisposition for the exact contract.
// Graduating an entry to specialized/absorbed is a per-family migration
// step, never a bulk edit.
//
// fixtures.final reference the bundle corpus (`rendering-bundles/<file>`)
// as seed evidence; dedicated shape fixtures under
// testing/fixtures/rendering-shapes/ join them as capture soaks + the
// extract script produce redacted minimal cases.
export const CLAUDE_RENDER_SHAPES = defineRenderShapeCatalog('claude', {
  'claude.entry.attachment.v1': defineRenderShape({
    id: 'claude.entry.attachment.v1',
    provider: 'claude',
    fingerprints: ["fp2-17325b53","fp2-1f43958e","fp2-20f22b8f","fp2-38e7ef3d","fp2-3ae4cf2b","fp2-40425c51","fp2-43858260","fp2-4d79e5d3","fp2-581ac6d5","fp2-60e3d224","fp2-6399aefe","fp2-69882ce4","fp2-753c33b9","fp2-83a3fbfd","fp2-8628c635","fp2-8feef6e3","fp2-abe64889","fp2-b0d9d248","fp2-b4071732","fp2-b8a64f27","fp2-bc298de8","fp2-c1d8a2a6","fp2-cdb2f73a","fp2-d192dbac","fp2-dd5cff49","fp2-e4e63295","fp2-f08b1406","fp2-f30522fc","fp2-f7b66ff2"],
    eventTypes: ["attachment"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'system' },
    why: 'Seeded from the 48-bundle corpus (121 sightings); structural variants share this id.',
  }),
  'claude.entry.pr-link.v1': defineRenderShape({
    id: 'claude.entry.pr-link.v1',
    provider: 'claude',
    fingerprints: ["fp2-696bfb91"],
    eventTypes: ["pr-link"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json","rendering-bundles/2026-06-14T14-02-05-796-a8ad1ebb.json","rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'system' },
    why: 'Seeded from the 48-bundle corpus (157 sightings); structural variants share this id.',
  }),
  'claude.entry.queue-operation.v1': defineRenderShape({
    id: 'claude.entry.queue-operation.v1',
    provider: 'claude',
    fingerprints: ["fp2-93af4392","fp2-ffa1daf8"],
    eventTypes: ["queue-operation"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T14-02-05-796-a8ad1ebb.json","rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json","rendering-bundles/2026-06-14T14-32-42-750-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'system' },
    why: 'Seeded from the 48-bundle corpus (85 sightings); structural variants share this id.',
  }),
  'claude.entry.system-compact-boundary.v1': defineRenderShape({
    id: 'claude.entry.system-compact-boundary.v1',
    provider: 'claude',
    fingerprints: ["fp2-d3594ad3"],
    eventTypes: ["system:compact_boundary"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-22T12-46-15-717-c973322e.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'system' },
    why: 'Seeded from the 48-bundle corpus (1 sightings); structural variants share this id.',
  }),
  'claude.entry.system-turn-duration.v1': defineRenderShape({
    id: 'claude.entry.system-turn-duration.v1',
    provider: 'claude',
    fingerprints: ["fp2-2c0c0341","fp2-624904d3","fp2-acba5abf","fp2-cb7091d5"],
    eventTypes: ["system:turn_duration"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'system' },
    why: 'Seeded from the 48-bundle corpus (69 sightings); structural variants share this id.',
  }),
  'claude.entry.user.v1': defineRenderShape({
    id: 'claude.entry.user.v1',
    provider: 'claude',
    fingerprints: ["fp2-688dff42","fp2-92c29c6f"],
    eventTypes: ["user"],
    planes: ["transcript-entry"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-21T19-19-55-972-62432945.json","rendering-bundles/2026-06-21T20-14-23-131-62432945.json","rendering-bundles/2026-06-22T12-34-16-431-2db014bc.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'system' },
    why: 'Seeded from the 48-bundle corpus (13 sightings); structural variants share this id.',
  }),
  'claude.semantic.agent.v1': defineRenderShape({
    id: 'claude.semantic.agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-279fd9c3","fp2-7148ba15","fp2-d06574fa","fp2-d36d2d0d"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: parsed semantic Agent input now routes through the same provider adapter/card as the committed operation; incomplete prefixes keep the visible generic stream until the strict Agent grammar closes.',
  }),
  'claude.semantic.askuserquestion.v1': defineRenderShape({
    id: 'claude.semantic.askuserquestion.v1',
    provider: 'claude',
    fingerprints: ["fp2-21c00403","fp2-af6fbebc"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-17T11-50-56-053-a6c70f19.json","rendering-bundles/2026-06-21T18-16-49-177-fc397785.json","rendering-bundles/2026-06-21T19-19-55-972-62432945.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'questions' },
    why: 'Seeded from the 48-bundle corpus (4 sightings); structural variants share this id.',
  }),
  'claude.semantic.bash.v1': defineRenderShape({
    id: 'claude.semantic.bash.v1',
    provider: 'claude',
    fingerprints: ["fp2-326d9120","fp2-42e564e8","fp2-9d6cf8fc","fp2-cad93e7b","fp2-ee539da9","fp2-f0bd83a7"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (132 sightings); structural variants share this id.',
  }),
  'claude.semantic.edit.v1': defineRenderShape({
    id: 'claude.semantic.edit.v1',
    provider: 'claude',
    fingerprints: ["fp2-2323238a","fp2-28bc3225","fp2-c29bd417","fp2-d152c062"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T14-02-05-796-a8ad1ebb.json","rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-29T11-38-28-652-42071335.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'code-edit' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (15 sightings); structural variants share this id.',
  }),
  'claude.semantic.enterworktree.v1': defineRenderShape({
    id: 'claude.semantic.enterworktree.v1',
    provider: 'claude',
    fingerprints: ["fp2-48eed2e4"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-29T11-38-28-652-42071335.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (1 sightings); structural variants share this id.',
  }),
  'claude.semantic.mcp-orchestration-close-agent.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-close-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-4789512c","fp2-a13b27bf","fp2-ecd79fdb"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-bundles/2026-06-29T14-11-47-099-1b2b5e96.json","rendering-bundles/2026-06-29T14-13-09-044-1b2b5e96.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: the exact mcp__agent_code__ namespace proves the source-controlled orchestration protocol; new 2026-07-17 prefix variants remain visible until parsed input is complete.',
  }),
  'claude.semantic.mcp-orchestration-close-run.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-close-run.v1',
    provider: 'claude',
    fingerprints: ["fp2-782d249b","fp2-b0effe07"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/agent-code-orchestration/final.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7 from the live capture plus the owned close-run schema; the curated fixture records that provenance because the frozen bundle corpus did not contain this semantic mirror.',
  }),
  'claude.semantic.mcp-orchestration-create-agent.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-create-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-23af1de7","fp2-78b9c8e2","fp2-7b34fd2f","fp2-7b63e36c","fp2-7ed23c16","fp2-e64f1cc9","fp2-eebdcf03"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-21T19-19-55-972-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: Agent Code create is provider-recognized by its exact MCP namespace and rendered by the shared owned-protocol view, never by the open-world MCP fallback.',
  }),
  'claude.semantic.mcp-orchestration-list-agents.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-list-agents.v1',
    provider: 'claude',
    fingerprints: ["fp2-74655986","fp2-a8b077ae","fp2-f0d1e7da"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-21T20-14-23-131-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: list-agent inputs share the owned protocol card; the newly observed prefix stays generic until the reducer provides authoritative parsed input.',
  }),
  'claude.semantic.mcp-orchestration-read-agent.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-read-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-cb2cb220"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: read-agent is an owned orchestration discovery operation, with bounded per-message disclosures and an exact raw protocol fallback inside the card.',
  }),
  'claude.semantic.mcp-orchestration-send-prompt.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-send-prompt.v1',
    provider: 'claude',
    fingerprints: ["fp2-0538cebb","fp2-c9fd7a40"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: send-prompt input is provider-owned only for the agent_code namespace; failures keep operation-specific diagnostics in the raw protocol disclosure.',
  }),
  'claude.semantic.mcp-orchestration-wait-agents.v1': defineRenderShape({
    id: 'claude.semantic.mcp-orchestration-wait-agents.v1',
    provider: 'claude',
    fingerprints: ["fp2-0ce1d5ee","fp2-0fa4ac05","fp2-93dec72c","fp2-cb45a301"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-21T20-14-23-131-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: wait results render bounded agent summaries and lazy child output; the 2026-07-17 complete-input variant is folded into the same visual operation.',
  }),
  'claude.semantic.notebookedit.v1': defineRenderShape({
    id: 'claude.semantic.notebookedit.v1',
    provider: 'claude',
    fingerprints: ["fp2-974fdedb","fp2-a64230ba"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'code-edit' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (2 sightings); structural variants share this id.',
  }),
  'claude.semantic.read.v1': defineRenderShape({
    id: 'claude.semantic.read.v1',
    provider: 'claude',
    fingerprints: ["fp2-3ad02d79","fp2-7e45af3e","fp2-f959f6c0","fp2-faf7aca7"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'GRADUATED Phase 7: complete semantic Read input is converted to the committed ToolUseBlock contract and routed through the same Claude read adapter/component; prefixes remain visible.',
  }),
  'claude.semantic.skill.v1': defineRenderShape({
    id: 'claude.semantic.skill.v1',
    provider: 'claude',
    fingerprints: ["fp2-690826ce","fp2-72e2f303"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tasks' },
    why: 'Seeded from the 48-bundle corpus (6 sightings); structural variants share this id.',
  }),
  'claude.semantic.taskcreate.v1': defineRenderShape({
    id: 'claude.semantic.taskcreate.v1',
    provider: 'claude',
    fingerprints: ["fp2-0203f177","fp2-072fd53b","fp2-15718172"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-22T09-05-45-698-7733b0fc.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tasks' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (16 sightings); structural variants share this id.',
  }),
  'claude.semantic.taskupdate.v1': defineRenderShape({
    id: 'claude.semantic.taskupdate.v1',
    provider: 'claude',
    fingerprints: ["fp2-083fb7d8","fp2-3159a259","fp2-37a1ba2a"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tasks' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (6 sightings); structural variants share this id.',
  }),
  'claude.semantic.text.v1': defineRenderShape({
    id: 'claude.semantic.text.v1',
    provider: 'claude',
    fingerprints: ["fp2-c5003421","fp2-f134003d"],
    eventTypes: ["text"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'prose' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (232 sightings); structural variants share this id.',
  }),
  'claude.semantic.thinking.v1': defineRenderShape({
    id: 'claude.semantic.thinking.v1',
    provider: 'claude',
    fingerprints: ["fp2-a006c766","fp2-e8268b73"],
    eventTypes: ["thinking"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'reasoning' },
    why: 'Seeded from the 48-bundle corpus (185 sightings); structural variants share this id.',
  }),
  'claude.semantic.toolsearch.v1': defineRenderShape({
    id: 'claude.semantic.toolsearch.v1',
    provider: 'claude',
    fingerprints: ["fp2-9cf197fc","fp2-c3b66ae8","fp2-ed0e9987"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7: parsed semantic ToolSearch reuses the committed structured discovery row and result adapter instead of maintaining a second live JSON grammar.',
  }),
  'claude.semantic.webfetch.v1': defineRenderShape({
    id: 'claude.semantic.webfetch.v1',
    provider: 'claude',
    fingerprints: ["fp2-02b29108","fp2-39f6fc6f"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/web-fetch/semantic-final.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7 from live capture: authoritative parsed input reuses the committed WebFetch adapter; the synthetic fixture preserves the captured structure without inventing a frozen-bundle claim.',
  }),
  'claude.semantic.websearch.v1': defineRenderShape({
    id: 'claude.semantic.websearch.v1',
    provider: 'claude',
    fingerprints: ["fp2-790c707c","fp2-befc9470"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/web-search/semantic-final.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7 from live capture: authoritative parsed input reuses the committed WebSearch adapter; streaming prefixes keep the bounded generic path until the query closes.',
  }),
  'claude.semantic.write.v1': defineRenderShape({
    id: 'claude.semantic.write.v1',
    provider: 'claude',
    fingerprints: ["fp2-80a4cece","fp2-ad91ef51","fp2-bb84f08f"],
    eventTypes: ["tool_use"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json","rendering-bundles/2026-06-14T14-32-42-750-a8ad1ebb.json","rendering-bundles/2026-06-14T14-32-54-340-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'code-edit' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (16 sightings); structural variants share this id.',
  }),
  'claude.tool-result.tool-result.v1': defineRenderShape({
    id: 'claude.tool-result.tool-result.v1',
    provider: 'claude',
    fingerprints: ["fp2-05148fe5","fp2-5088f736","fp2-ac6ff7c0","fp2-cfd69380"],
    eventTypes: ["tool_result"],
    planes: ["committed-tool-result"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tool-result' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (394 sightings); structural variants share this id.',
  }),
  'claude.tool-use.agent.v1': defineRenderShape({
    id: 'claude.tool-use.agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-0406b30d","fp2-29d6969a","fp2-76182cb6","fp2-8f84787b"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/agent/final.json","rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Observed across the frozen corpus and fresh 2026-07-16 recordings; Phase 7 moves the built-in Claude Agent grammar off the shared spawn interceptor into a provider-owned paired card.',
  }),
  'claude.tool-use.askuserquestion.v1': defineRenderShape({
    id: 'claude.tool-use.askuserquestion.v1',
    provider: 'claude',
    fingerprints: ["fp2-78de3d3e"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-21T18-16-49-177-fc397785.json","rendering-bundles/2026-06-21T19-19-55-972-62432945.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'questions' },
    why: 'Seeded from the 48-bundle corpus (3 sightings); structural variants share this id.',
  }),
  'claude.tool-use.bash.v1': defineRenderShape({
    id: 'claude.tool-use.bash.v1',
    provider: 'claude',
    fingerprints: ["fp2-3da1120c","fp2-490f20a2","fp2-c4cd6b80","fp2-cb2c6fd2","fp2-eab9de5c","fp2-fd75288a"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (197 sightings); structural variants share this id.',
  }),
  'claude.tool-use.edit.v1': defineRenderShape({
    id: 'claude.tool-use.edit.v1',
    provider: 'claude',
    fingerprints: ["fp2-8bad26f1"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json","rendering-bundles/2026-06-14T14-02-05-796-a8ad1ebb.json","rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (12 sightings); structural variants share this id. GRADUATED 2026-07-16: cut over to the code-edit protocol (adapter + CodeEditView); receipts must name this renderer or the sighting files as misrouted',
  }),
  'claude.tool-use.lsp.v1': defineRenderShape({
    id: 'claude.tool-use.lsp.v1',
    provider: 'claude',
    fingerprints: ["fp2-296283bb"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'lsp' },
    why: 'TODO(phase-8-evidence): LSP was initially bucketed with reads because it returns discovery-like text, but its workspace/language-server lifecycle belongs to Phase 8 and has only one live sighting with no durable fixture; do not fabricate a Phase 7 adapter.',
  }),
  'claude.tool-use.mcp-get-projects-list.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-get-projects-list.v1',
    provider: 'claude',
    fingerprints: ["fp2-51ac2727"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'claude.tool-use.mcp-list-calendars.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-list-calendars.v1',
    provider: 'claude',
    fingerprints: ["fp2-40794dd0"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'claude.tool-use.mcp-list-labels.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-list-labels.v1',
    provider: 'claude',
    fingerprints: ["fp2-cbe2bb34"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'claude.tool-use.mcp-orchestration-close-agent.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-close-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-8d5a374c"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-29T14-11-47-099-1b2b5e96.json","rendering-bundles/2026-06-29T14-13-09-044-1b2b5e96.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: the provider adapter proves the exact agent_code namespace before the owned orchestration close card can claim this committed operation.',
  }),
  'claude.tool-use.mcp-orchestration-close-run.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-close-run.v1',
    provider: 'claude',
    fingerprints: ["fp2-d51238ff"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-21T18-16-49-177-fc397785.json","rendering-bundles/2026-06-21T19-19-55-972-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: close-run uses the source-controlled Agent Code result contract and retains closed/skipped session ids in the raw protocol disclosure.',
  }),
  'claude.tool-use.mcp-orchestration-create-agent.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-create-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-3bb32d92","fp2-89e9a6cc","fp2-b50901e3","fp2-e715b7f7","fp2-f53af93d","fp2-fdc02391"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-21T19-19-55-972-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: committed create-agent now bypasses the legacy name-only TaskSubagentRow and renders the owned Agent Code lifecycle/result protocol.',
  }),
  'claude.tool-use.mcp-orchestration-list-agents.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-list-agents.v1',
    provider: 'claude',
    fingerprints: ["fp2-5ba767ef","fp2-f4ce844a"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-21T18-16-49-177-fc397785.json","rendering-bundles/2026-06-21T20-14-23-131-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: list results use a capped agent table while the full structured protocol stays available behind a lazy disclosure.',
  }),
  'claude.tool-use.mcp-orchestration-read-agent.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-read-agent.v1',
    provider: 'claude',
    fingerprints: ["fp2-37f59a8d","fp2-e6ed123a"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-29T14-11-47-099-1b2b5e96.json","rendering-bundles/2026-06-29T14-13-09-044-1b2b5e96.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: Agent Code output is source-bounded and then DOM-bounded again with per-agent/per-message lazy disclosures; parser drift falls through visibly.',
  }),
  'claude.tool-use.mcp-orchestration-send-prompt.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-send-prompt.v1',
    provider: 'claude',
    fingerprints: ["fp2-4f2b8052"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json","rendering-bundles/2026-06-29T14-11-47-099-1b2b5e96.json","rendering-bundles/2026-06-29T14-13-09-044-1b2b5e96.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: prompt text is collapsed/lazy, target identity remains visible, and uncertain delivery diagnostics are retained instead of collapsed to success/failure folklore.',
  }),
  'claude.tool-use.mcp-orchestration-wait-agents.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-orchestration-wait-agents.v1',
    provider: 'claude',
    fingerprints: ["fp2-358c4c4f","fp2-447639d2","fp2-59ede605","fp2-b2fe7f1d"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-bundles/2026-06-21T17-32-48-749-5e75540c.json","rendering-bundles/2026-06-21T18-16-49-177-fc397785.json","rendering-bundles/2026-06-21T20-14-23-131-62432945.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: wait is an owned multi-agent protocol with capped rows and nested lazy outputs; the 2026-07-17 cap-field variant joins the same visual operation.',
  }),
  'claude.tool-use.mcp-ref-search-documentation.v1': defineRenderShape({
    id: 'claude.tool-use.mcp-ref-search-documentation.v1',
    provider: 'claude',
    fingerprints: ["fp2-12a71d56"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'claude.tool-use.monitor.v1': defineRenderShape({
    id: 'claude.tool-use.monitor.v1',
    provider: 'claude',
    fingerprints: ["fp2-3ccd9ea4"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tasks' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'claude.tool-use.notebookedit.v1': defineRenderShape({
    id: 'claude.tool-use.notebookedit.v1',
    provider: 'claude',
    fingerprints: ["fp2-cc6cefa5"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'code-edit' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'claude.tool-use.read.v1': defineRenderShape({
    id: 'claude.tool-use.read.v1',
    provider: 'claude',
    fingerprints: ["fp2-17828ea4","fp2-4f808916","fp2-668e025e","fp2-9cdbe334"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/read/final.json","rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T13-59-16-931-4757ae44.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Observed in the frozen corpus and live recordings; Phase 7 routes the committed invocation through the provider-owned Read component.',
  }),
  'claude.tool-use.schedulewakeup.v1': defineRenderShape({
    id: 'claude.tool-use.schedulewakeup.v1',
    provider: 'claude',
    fingerprints: ["fp2-bbd55bdc"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-07-07T13-17-20-472-5b19529f.json","rendering-bundles/2026-07-07T13-17-48-452-5b19529f.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tasks' },
    why: 'Seeded from the 48-bundle corpus (2 sightings); structural variants share this id.',
  }),
  'claude.tool-use.skill.v1': defineRenderShape({
    id: 'claude.tool-use.skill.v1',
    provider: 'claude',
    fingerprints: ["fp2-c651173c"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tasks' },
    why: 'Seeded from the 48-bundle corpus (5 sightings); structural variants share this id.',
  }),
  'claude.tool-use.taskcreate.v1': defineRenderShape({
    id: 'claude.tool-use.taskcreate.v1',
    provider: 'claude',
    fingerprints: ["fp2-af9ab62f"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-22T09-05-45-698-7733b0fc.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tasks' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (14 sightings); structural variants share this id.',
  }),
  'claude.tool-use.taskget.v1': defineRenderShape({
    id: 'claude.tool-use.taskget.v1',
    provider: 'claude',
    fingerprints: ["fp2-1c76760b"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tasks' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'claude.tool-use.taskoutput.v1': defineRenderShape({
    id: 'claude.tool-use.taskoutput.v1',
    provider: 'claude',
    fingerprints: ["fp2-8232b4d2"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'claude.tool-use.taskstop.v1': defineRenderShape({
    id: 'claude.tool-use.taskstop.v1',
    provider: 'claude',
    fingerprints: ["fp2-8d4dfa22"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'claude.tool-use.taskupdate.v1': defineRenderShape({
    id: 'claude.tool-use.taskupdate.v1',
    provider: 'claude',
    fingerprints: ["fp2-ddd6329d"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tasks' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (5 sightings); structural variants share this id.',
  }),
  'claude.tool-use.toolsearch.v1': defineRenderShape({
    id: 'claude.tool-use.toolsearch.v1',
    provider: 'claude',
    fingerprints: ["fp2-68bade64"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/tool-search/final.json","rendering-bundles/2026-06-04T09-09-57-625-4177cefb.json","rendering-bundles/2026-06-04T09-14-29-649-4177cefb.json","rendering-bundles/2026-06-14T15-52-20-411-b728adb8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Observed in the frozen corpus and live recordings; Phase 7 routes the committed invocation through the provider-owned ToolSearch component.',
  }),
  'claude.tool-use.webfetch.v1': defineRenderShape({
    id: 'claude.tool-use.webfetch.v1',
    provider: 'claude',
    fingerprints: ["fp2-9382b7f6"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/web-fetch/final.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Observed in fresh 2026-07-16 recordings; Phase 7 routes committed WebFetch invocation and paired string output through provider-owned components.',
  }),
  'claude.tool-use.websearch.v1': defineRenderShape({
    id: 'claude.tool-use.websearch.v1',
    provider: 'claude',
    fingerprints: ["fp2-c5a5c976"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/claude/web-search/final.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Observed in fresh 2026-07-16 recordings; Phase 7 routes committed WebSearch invocation and paired string output through provider-owned components.',
  }),
  'claude.tool-use.write.v1': defineRenderShape({
    id: 'claude.tool-use.write.v1',
    provider: 'claude',
    fingerprints: ["fp2-471cb5b5"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-14T14-25-07-012-a8ad1ebb.json","rendering-bundles/2026-06-14T14-32-42-750-a8ad1ebb.json","rendering-bundles/2026-06-14T14-32-54-340-a8ad1ebb.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'claude.rows.dispatch' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (16 sightings); structural variants share this id. GRADUATED 2026-07-16: cut over to the code-edit protocol (adapter + CodeEditView); receipts must name this renderer or the sighting files as misrouted',
  }),})

export type ClaudeRenderShapeId = keyof typeof CLAUDE_RENDER_SHAPES
