import { fireEvent, render, screen } from '@testing-library/react'
import { describe, expect, it } from 'vitest'

import { CodexImageGenerationRow } from '.'

describe('CodexImageGenerationRow', () => {
  it('renders lifecycle immediately and generated bytes only after disclosure', () => {
    render(<CodexImageGenerationRow model={{
      status: 'completed',
      revisedPrompt: 'A small blue lighthouse',
      result: 'YWJj',
    }} />)

    expect(screen.getByText(/Image generation/)).toBeInTheDocument()
    expect(screen.getByText('completed')).toBeInTheDocument()
    expect(screen.queryByRole('img')).not.toBeInTheDocument()
    fireEvent.click(screen.getByText(/Generated image/))
    expect(screen.getByRole('img')).toHaveAttribute('src', 'data:image/png;base64,YWJj')
  })
})
