import { describe, expect, it } from 'vitest'

import { firstUnwrappedPrompt, unwrapUserText } from './unwrap.js'

// Every literal below is the opening of a real record from the corpus (ids in
// comments) with its private remainder replaced; the assertions are about the
// prefix rule, which is exactly what the redaction preserves.
describe('unwrapUserText', () => {
  it('returns a dictated prompt without its stt wrapper', () => {
    // claude bcc80949 first prompt
    const raw = '<stt note="Speech-to-text; may contain transcription mistakes.">\n We have a lot of things to do\n</stt>'
    expect(unwrapUserText(raw)).toEqual({ text: 'We have a lot of things to do', wrapper: 'stt' })
  })

  it('returns a PASTED prompt without Claude\'s envelope, instead of dropping it (#1059)', () => {
    // The real shape Claude Code 2.1.278 commits, closing tag id included.
    // Left off the closed list it fell to the generic `<`-prefix rule and was
    // DROPPED, so View Prompts said "No visible user prompts found for this
    // session" while the feed above it showed them, and the conversations
    // picker labelled the session from a later, shorter prompt — or not at all.
    const raw = '<pasted_content id="cade">\nAdd to the list of things to resolve pre launch\n</pasted_content id="cade">'
    expect(unwrapUserText(raw)).toEqual({
      text: 'Add to the list of things to resolve pre launch',
      wrapper: 'pasted-content',
    })
  })

  it('labels a conversation from a pasted FIRST prompt (#1059)', () => {
    // firstUnwrappedPrompt walks until something unwraps. With the envelope
    // dropped it skipped past the opening prompt — the longest one, the one
    // worth labelling by — and took a later line instead.
    const pasted = '<pasted_content id="cade">\nPort the renderer to the new pipeline\n</pasted_content id="cade">'
    expect(firstUnwrappedPrompt([pasted, 'and then run the tests'])).toEqual({
      text: 'Port the renderer to the new pipeline',
      wrapper: 'pasted-content',
    })
  })

  it('still drops an EMPTY envelope rather than labelling with a blank', () => {
    expect(unwrapUserText('<pasted_content id="cade">\n\n</pasted_content id="cade">')).toBeNull()
  })

  it('does not unwrap an ambiguous or partial envelope', () => {
    // unwrapClaudePastedContent refuses to guess: two sibling blocks sharing
    // an id, and a prompt that merely CONTAINS the tag, both stay wrapped —
    // and therefore stay excluded by the `<` rule, as before.
    const siblings = '<pasted_content id="x">\na\n</pasted_content id="x"><pasted_content id="x">\nb\n</pasted_content id="x">'
    expect(unwrapUserText(siblings)).toBeNull()
    expect(unwrapUserText('see <pasted_content id="x">\na\n</pasted_content id="x">')).toEqual({
      text: 'see <pasted_content id="x"> a </pasted_content id="x">',
      wrapper: null,
    })
  })

  it('returns the task inside an orchestration handoff', () => {
    // claude 54e5b227 / codex 01a08ddd first prompt
    const raw = '<orchestration-handoff>\nYou are now an orchestrated child agent in Agent Code.\nFollow only the new task and instructions below.\n</orchestration-handoff>\n\n<task>\nReview the Grok lifecycle.\n</task>'
    expect(unwrapUserText(raw)).toEqual({ text: 'Review the Grok lifecycle.', wrapper: 'orchestration-handoff' })
  })

  it('treats a handoff without a task block as the text after the wrapper', () => {
    const raw = '<orchestration-handoff>\nYou are now an orchestrated child agent.\n</orchestration-handoff>\n\nDo the thing.'
    expect(unwrapUserText(raw)).toEqual({ text: 'Do the thing.', wrapper: 'orchestration-handoff' })
  })

  it('marks a provider-switch handoff summary as projected and labels it by its first heading', () => {
    // claude 05b2f009 first prompt
    const raw = '# Handoff Summary\n## Current objective\nPlan and eventually implement a redesigned picker'
    expect(unwrapUserText(raw)).toEqual({ text: 'Current objective', wrapper: 'projected-handoff' })
    expect(unwrapUserText('# Portable handoff summary\n\n## Current state\nThe active work is complete')).toEqual({ text: 'Current state', wrapper: 'projected-handoff' })
  })

  it.each([
    '# AGENTS.md instructions for /Users/x/y\n\n<INSTRUCTIONS>',
    '<environment_context>\n<cwd>/x</cwd>',
    '<command-name>/compact</command-name>\n<command-message>compact</command-message>',
    '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.',
    '<local-command-stdout>Set model to Fable</local-command-stdout>',
    '<recommended_plugins>\nHere is a list of plugins',
    '<user_instructions>x</user_instructions>',
    '<system-reminder>x</system-reminder>',
    '<task-notification>\n<task-id>x</task-id>',
    'This session is being continued from a previous conversation that ran out of context.',
    '<unknown-wrapper>anything</unknown-wrapper>',
    '   ',
  ])('is not a prompt: %s', raw => {
    expect(unwrapUserText(raw)).toBeNull()
  })

  it('returns plain text unchanged apart from whitespace collapsing', () => {
    expect(unwrapUserText('  break down this project \n')).toEqual({ text: 'break down this project', wrapper: null })
  })
})

describe('firstUnwrappedPrompt', () => {
  it('skips injected messages to reach the real first prompt', () => {
    // codex 01a0889d as the old lister saw it: AGENTS.md first, prompt second
    expect(firstUnwrappedPrompt(['# AGENTS.md instructions for /x\n\n<INSTRUCTIONS>', 'break down this project'])).toEqual({ text: 'break down this project', wrapper: null })
    expect(firstUnwrappedPrompt(['<command-name>/compact</command-name>'])).toBeNull()
    expect(firstUnwrappedPrompt([])).toBeNull()
  })
})
