import { describe, expect, it } from 'vitest'

import { firstUnwrappedPrompt, unwrapUserText } from './unwrap.js'

// Every literal below is the opening of a real record from the corpus (ids in
// comments) with its private remainder replaced; the assertions are about the
// prefix rule, which is exactly what the redaction preserves.
describe('unwrapUserText', () => {
  it('returns a dictated prompt without its stt wrapper', () => {
    // claude bcc80949 first prompt
    const raw = '<stt note="Speech-to-text; may contain transcription mistakes.">\n We have a lot of things to do\n</stt>'
    expect(unwrapUserText(raw)).toEqual({ text: 'We have a lot of things to do', wrapper: 'stt' })
  })

  it('returns the task inside an orchestration handoff', () => {
    // claude 54e5b227 / codex 01a08ddd first prompt
    const raw = '<orchestration-handoff>\nYou are now an orchestrated child agent in Agent Code.\nFollow only the new task and instructions below.\n</orchestration-handoff>\n\n<task>\nReview the Grok lifecycle.\n</task>'
    expect(unwrapUserText(raw)).toEqual({ text: 'Review the Grok lifecycle.', wrapper: 'orchestration-handoff' })
  })

  it('treats a handoff without a task block as the text after the wrapper', () => {
    const raw = '<orchestration-handoff>\nYou are now an orchestrated child agent.\n</orchestration-handoff>\n\nDo the thing.'
    expect(unwrapUserText(raw)).toEqual({ text: 'Do the thing.', wrapper: 'orchestration-handoff' })
  })

  it('marks a provider-switch handoff summary as projected and labels it by its first heading', () => {
    // claude 05b2f009 first prompt
    const raw = '# Handoff Summary\n## Current objective\nPlan and eventually implement a redesigned picker'
    expect(unwrapUserText(raw)).toEqual({ text: 'Current objective', wrapper: 'projected-handoff' })
    expect(unwrapUserText('# Portable handoff summary\n\n## Current state\nThe active work is complete')).toEqual({ text: 'Current state', wrapper: 'projected-handoff' })
  })

  it.each([
    '# AGENTS.md instructions for /Users/x/y\n\n<INSTRUCTIONS>',
    '<environment_context>\n<cwd>/x</cwd>',
    '<command-name>/compact</command-name>\n<command-message>compact</command-message>',
    '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.',
    '<local-command-stdout>Set model to Fable</local-command-stdout>',
    '<recommended_plugins>\nHere is a list of plugins',
    '<user_instructions>x</user_instructions>',
    '<system-reminder>x</system-reminder>',
    '<task-notification>\n<task-id>x</task-id>',
    '<unknown-wrapper>anything</unknown-wrapper>',
    '   ',
  ])('is not a prompt: %s', raw => {
    expect(unwrapUserText(raw)).toBeNull()
  })

  it('returns plain text unchanged apart from whitespace collapsing', () => {
    expect(unwrapUserText('  break down this project \n')).toEqual({ text: 'break down this project', wrapper: null })
  })
})

describe('firstUnwrappedPrompt', () => {
  it('skips injected messages to reach the real first prompt', () => {
    // codex 01a0889d as the old lister saw it: AGENTS.md first, prompt second
    expect(firstUnwrappedPrompt(['# AGENTS.md instructions for /x\n\n<INSTRUCTIONS>', 'break down this project'])).toEqual({ text: 'break down this project', wrapper: null })
    expect(firstUnwrappedPrompt(['<command-name>/compact</command-name>'])).toBeNull()
    expect(firstUnwrappedPrompt([])).toBeNull()
  })
})
