// agent-activity-redaction-policy.ts — the privacy pass over the agent-activity runtime corpus (#1296).
//
// WHY a module of its own: the extractor writes runtime-states.json through this pass, and the
// committed fixture must be EXACTLY that output. Review of #1353 found the first committed file had
// been touched up by hand (its placeholders were impossible outputs of the script), so a re-run
// produced a different file. Keeping the pass importable lets the fixture be regenerated from the
// pre-redaction corpus in git history without re-reading the debug bundles, and lets anyone check
// that "the committed file is the script's output" instead of trusting the provenance string.
//
// WHY text is kept as structure: the row model reads none of this TEXT — it branches on statuses,
// phases, delivery kinds, queue LENGTHS and timestamps — so every non-space character of a text field
// becomes `x` and lengths and line shapes survive (the same-length rule keeps byte offsets and widths
// in anything derived honest).

/**
 * The fixture's own account of itself. It lives here, beside the pass it describes, so the
 * regeneration from git history and the extractor write the same words.
 */
export const RUNTIME_STATES_PROVENANCE =
  'Every `state-snapshot.json` in the local debug-bundle corpus: the renderer\'s own SessionRuntime for one real session at the moment a bundle was taken, written by the app. Generated by scripts/extract-agent-activity-runtimes.mts — do not hand-edit, re-run it. The four screen mirrors are removed and their lengths recorded (see the script header); personal text (prompts, drafts, suggestions, subagent descriptions, streaming baselines, branch names) is filled with x at its own length, the home user becomes a same-length placeholder, and each non-Agent-Code project name becomes its own same-length placeholder with the rest of its path x-filled (scripts/agent-activity-redaction-policy.ts, #1296); every other field is verbatim, including the ugly ones.'

/**
 * Fields whose whole value is personal text.
 *
 * WHY `branch` (review of #1353): branch names of private repos said what those projects were doing
 * ("docs/hermes-runtime-architecture"). Agent Code's own branches are public, but a branch field
 * does not say which repo it belongs to, so every branch is filled — over-redaction is free here.
 */
const TEXT_FIELDS = new Set(['branch', 'content', 'draftInput', 'prompt', 'text', 'description', 'streamingBaseline'])

function padded(tag: string, length: number): string {
  // A tag longer than the name would change the length (or, sliced, collide with another tag).
  // Fail loudly instead: a regeneration that cannot keep the rule must not write a file.
  if (tag.length > length) throw new Error(`cannot redact a ${length}-character name with tag ${tag}`)
  return (tag + '-'.repeat(length)).slice(0, length)
}

export function createAgentActivityRedactor(homeUser: string): (value: unknown) => unknown {
  // WHY one placeholder per distinct name (review of #1353): a placeholder derived from the length
  // alone gave `startup` and `win-win` (both 7 characters) the same `project`, merging two private
  // projects into one in every regeneration. The index is assigned in walk order, which is
  // deterministic for the same input, so a re-run over the same corpus writes the same file.
  const projects = new Map<string, string>()
  const projectPlaceholder = (name: string): string => {
    let placeholder = projects.get(name)
    if (placeholder === undefined) {
      placeholder = padded(`p${projects.size.toString(36)}`, name.length)
      projects.set(name, placeholder)
    }
    return placeholder
  }

  const redactPathText = (value: string): string => {
    let out = homeUser ? value.split(homeUser).join(padded('fixture-home'.slice(0, homeUser.length), homeUser.length)) : value
    // The name is the first path segment after `Development/` (or the whole dash-encoded tail of a
    // Claude projects dir, `-Development-<name>`). WHY the rest of the path goes too (review of
    // #1353): worktree names under a private repo (`win-win/.claude/worktrees/simplify`) are as
    // telling as branch names. Separators are kept so the path's shape survives. Agent Code paths
    // are the public repo and stay verbatim — the corpus is about this app.
    out = out.replace(/(Development[-/])([^\s/"'`]+)((?:\/[^\s"'`]*)?)/g, (match, prefix: string, name: string, rest: string) =>
      name.startsWith('agent-code') ? match : prefix + projectPlaceholder(name) + rest.replace(/[^/]/g, 'x'))
    return out
  }

  const redact = (value: unknown, key?: string): unknown => {
    if (Array.isArray(value)) return value.map(item => redact(item, key))
    if (value && typeof value === 'object') {
      return Object.fromEntries(Object.entries(value).map(([k, v]) => [redactPathText(k), redact(v, k)]))
    }
    if (typeof value === 'string') {
      return key !== undefined && TEXT_FIELDS.has(key) ? value.replace(/\S/g, 'x') : redactPathText(value)
    }
    return value
  }
  return value => redact(value)
}
