// agent-activity-redaction-policy.ts — the privacy pass over the agent-activity runtime corpus (#1296).
//
// WHY a module of its own: the extractor writes runtime-states.json through this pass, and the
// committed fixture must be EXACTLY that output. Review of #1353 found the first committed file had
// been touched up by hand (its placeholders were impossible outputs of the script), so a re-run
// produced a different file. Keeping the pass importable lets the fixture be regenerated from the
// pre-redaction corpus in git history without re-reading the debug bundles, and lets anyone check
// that "the committed file is the script's output" instead of trusting the provenance string.
//
// WHY text is kept as structure: the row model reads none of this TEXT — it branches on statuses,
// phases, delivery kinds, queue LENGTHS and timestamps — so every non-space character of a text field
// becomes `x` and lengths and line shapes survive (the same-length rule keeps byte offsets and widths
// in anything derived honest).

/**
 * The fixture's own account of itself. It lives here, beside the pass it describes, so the
 * regeneration from git history and the extractor write the same words.
 */
export const RUNTIME_STATES_PROVENANCE =
  'Every `state-snapshot.json` in the local debug-bundle corpus: the renderer\'s own SessionRuntime for one real session at the moment a bundle was taken, written by the app. Generated by scripts/extract-agent-activity-runtimes.mts — do not hand-edit, re-run it. The four screen mirrors are removed and their lengths recorded (see the script header); personal text (prompts, drafts, suggestions, subagent descriptions, streaming baselines, branch names) is filled with x at its own length, the home user becomes a same-length placeholder, and each project other than the public agent-code repo (exact name) becomes its own same-length placeholder, and so does each segment of the rest of its path (scripts/agent-activity-redaction-policy.ts, #1296; regenerate only with --redact-from <file> --home-user <recorder>); every other field is verbatim, including the ugly ones.'

/**
 * Fields whose whole value is personal text.
 *
 * WHY `branch` (review of #1353): branch names of private repos said what those projects were doing
 * ("docs/hermes-runtime-architecture"). Agent Code's own branches are public, but a branch field
 * does not say which repo it belongs to, so every branch is filled — over-redaction is free here.
 */
const TEXT_FIELDS = new Set(['branch', 'content', 'draftInput', 'prompt', 'text', 'description', 'streamingBaseline'])

const PUBLIC_PROJECT = 'agent-code'

/** The same-length stand-in for the recorder's home user (`fixture-home` for a 12-character name). */
export function homePlaceholder(homeUser: string): string {
  return padded('fixture-home'.slice(0, homeUser.length), homeUser.length)
}

function padded(tag: string, length: number): string {
  // A tag longer than the name would change the length (or, sliced, collide with another tag).
  // Fail loudly instead: a regeneration that cannot keep the rule must not write a file.
  if (tag.length > length) throw new Error(`cannot redact a ${length}-character name with tag ${tag}`)
  return (tag + '-'.repeat(length)).slice(0, length)
}

export function createAgentActivityRedactor(homeUser: string): (value: unknown) => unknown {
  // WHY one placeholder per distinct name (review of #1353): a placeholder derived from the length
  // alone gave `startup` and `win-win` (both 7 characters) the same `project`, merging two private
  // projects into one in every regeneration. The index is assigned in walk order, which is
  // deterministic for the same input, so a re-run over the same corpus writes the same file.
  const projects = new Map<string, string>()
  const projectPlaceholder = (name: string): string => {
    let placeholder = projects.get(name)
    if (placeholder === undefined) {
      placeholder = padded(`p${projects.size.toString(36)}`, name.length)
      projects.set(name, placeholder)
    }
    return placeholder
  }

  // WHY each segment under a private project gets its own placeholder too (steering q74 regeneration):
  // x-filling the tail made `agent-code-audit-worktrees/commands-ui-shell` and `.../headless-packages`
  // (same length) the same string. As object KEYS (workActivity.touched is keyed by path) that merged
  // two entries into one — silent data loss the byte-length check caught. Same walk-order rule as
  // projects: deterministic for the same input.
  const segments = new Map<string, string>()
  const segmentPlaceholder = (segment: string): string => {
    if (segment === '') return segment
    let placeholder = segments.get(segment)
    if (placeholder === undefined) {
      const tag = `s${segments.size.toString(36)}`
      // A segment shorter than its tag is x-filled; the key-collision check in `redact` refuses the
      // file if that ever makes two keys equal.
      placeholder = tag.length > segment.length ? 'x'.repeat(segment.length) : (tag + 'x'.repeat(segment.length)).slice(0, segment.length)
      segments.set(segment, placeholder)
    }
    return placeholder
  }

  const redactPathText = (value: string): string => {
    let out = homeUser ? value.split(homeUser).join(homePlaceholder(homeUser)) : value
    // The name is the first path segment after `Development/` (or the whole dash-encoded tail of a
    // Claude projects dir, `-Development-<name>`). WHY the rest of the path goes too (review of
    // #1353): worktree names under a private repo (`win-win/.claude/worktrees/simplify`) are as
    // telling as branch names. Separators are kept so the path's shape survives. Agent Code paths
    // are the public repo and stay verbatim — the corpus is about this app.
    //
    // WHY the exact segment and not a prefix (review of #1353, steering q74): `startsWith` exempted
    // any private project whose name merely begins with `agent-code` (`agent-code-private`). Sibling
    // checkouts of the public repo named `agent-code-<task>` are redacted too as a result — over-
    // redaction costs nothing here, since the row model reads no path.
    out = out.replace(/(Development[-/])([^\s/"'`]+)((?:\/[^\s"'`]*)?)/g, (match, prefix: string, name: string, rest: string) =>
      name === PUBLIC_PROJECT ? match : prefix + projectPlaceholder(name) + rest.split('/').map(segmentPlaceholder).join('/'))
    return out
  }

  const redact = (value: unknown, key?: string): unknown => {
    if (Array.isArray(value)) return value.map(item => redact(item, key))
    if (value && typeof value === 'object') {
      const entries = Object.entries(value).map(([k, v]) => [redactPathText(k), redact(v, k)] as const)
      // Fail closed on a key collision: Object.fromEntries would silently keep only the last entry.
      if (new Set(entries.map(([k]) => k)).size !== entries.length) {
        throw new Error('redaction made two object keys equal; refusing to merge their entries')
      }
      return Object.fromEntries(entries)
    }
    if (typeof value === 'string') {
      return key !== undefined && TEXT_FIELDS.has(key) ? value.replace(/\S/g, 'x') : redactPathText(value)
    }
    return value
  }
  return value => redact(value)
}

/**
 * The `--home-user` a `--redact-from` run must be given, validated BEFORE anything is read or written.
 *
 * WHY required (steering q74): the pre-redaction fixture holds the RECORDER's home path. Defaulting to
 * the user running the script leaves that path intact on any other checkout, and writes it into the
 * tracked fixture. A name with a separator, or an empty one, cannot be a macOS short user name.
 */
export function requireHomeUser(argv: readonly string[]): string {
  const index = argv.indexOf('--home-user')
  const value = index === -1 ? undefined : argv[index + 1]
  if (value === undefined || value.trim() === '' || value.startsWith('--') || /[/\\\s]/.test(value)) {
    throw new Error('--redact-from needs --home-user <the recorder\'s short user name>; refusing to guess it')
  }
  return value
}

/**
 * Refuse output that still holds a home directory other than the placeholder.
 *
 * WHY a check on the RESULT and not only on the flag: a wrong `--home-user` (or a live extraction on
 * a machine whose bundles were copied from another user) would pass any flag check and still leave
 * `/Users/<someone>` in the file. This runs on the redacted text right before it is written.
 */
export function assertNoForeignHome(redactedJson: string, homeUser: string): void {
  const allowed = homeUser === '' ? undefined : homePlaceholder(homeUser)
  const foreign = new Set<string>()
  // `/Users/<name>` and `/home/<name>`, plus Claude's dash-encoded projects dir `-Users-<name>-`.
  for (const match of redactedJson.matchAll(/(?:\/(?:Users|home)\/([^/"\s]+))|(?:-Users-([^-"\s/]+)-)/g)) {
    const name = match[1] ?? match[2]!
    if (name !== allowed && !(allowed?.startsWith(`${name}-`) ?? false)) foreign.add(name)
  }
  if (foreign.size > 0) throw new Error(`redacted output still names ${foreign.size} home director${foreign.size === 1 ? 'y' : 'ies'}; not writing it`)
}
