// agent-activity-redaction-policy.ts — the privacy pass over the agent-activity runtime corpus (#1296).
//
// WHY a module of its own: the extractor writes runtime-states.json through this pass, and the
// committed fixture must be EXACTLY that output. Review of #1353 found the first committed file had
// been touched up by hand (its placeholders were impossible outputs of the script), so a re-run
// produced a different file. Keeping the pass importable lets the fixture be regenerated from the
// pre-redaction corpus in git history without re-reading the debug bundles, and lets anyone check
// that "the committed file is the script's output" instead of trusting the provenance string.
//
// WHY text is kept as structure: the row model reads none of this TEXT — it branches on statuses,
// phases, delivery kinds, queue LENGTHS and timestamps — so every non-space character of a text field
// becomes `x` and lengths and line shapes survive (the same-length rule keeps byte offsets and widths
// in anything derived honest).

/**
 * The fixture's own account of itself. It lives here, beside the pass it describes, so the
 * regeneration from git history and the extractor write the same words.
 */
export const RUNTIME_STATES_PROVENANCE =
  'Every `state-snapshot.json` in the local debug-bundle corpus: the renderer\'s own SessionRuntime for one real session at the moment a bundle was taken, written by the app. Generated by scripts/extract-agent-activity-runtimes.mts — do not hand-edit, re-run it. The four screen mirrors are removed and their lengths recorded (see the script header); personal text (prompts, drafts, suggestions, subagent descriptions, streaming baselines, branch names) is filled with x at its own length, the home user becomes a same-length placeholder, and each project other than the public agent-code repo (exact name) becomes its own same-length placeholder, and so does each segment of the rest of its path (scripts/agent-activity-redaction-policy.ts, #1296; regenerate only with --redact-from <file> --home-user <recorder>); every other field is verbatim, including the ugly ones.'

/**
 * Fields whose whole value is personal text.
 *
 * WHY `branch` (review of #1353): branch names of private repos said what those projects were doing
 * ("docs/hermes-runtime-architecture"). Agent Code's own branches are public, but a branch field
 * does not say which repo it belongs to, so every branch is filled — over-redaction is free here.
 */
const TEXT_FIELDS = new Set(['branch', 'content', 'draftInput', 'prompt', 'text', 'description', 'streamingBaseline'])

const PUBLIC_PROJECT = 'agent-code'

/** The macOS home folders a dash-encoded project dir may continue with (see assertHomesBelongTo). */
// Dot folders (`.claude` → `--claude`) are deliberately absent: the empty component after the
// user makes them the most ambiguous form, and the recorded corpus has none, so they refuse.
const HOME_FOLDERS = new Set(['Desktop', 'Development', 'Documents', 'Downloads', 'Developer', 'Projects', 'Library'])

/** The same-length stand-in for the recorder's home user (`fixture-home` for a 12-character name). */
export function homePlaceholder(homeUser: string): string {
  return padded('fixture-home'.slice(0, homeUser.length), homeUser.length)
}

function padded(tag: string, length: number): string {
  // A tag longer than the name would change the length (or, sliced, collide with another tag).
  // Fail loudly instead: a regeneration that cannot keep the rule must not write a file.
  if (tag.length > length) throw new Error(`cannot redact a ${length}-character name with tag ${tag}`)
  return (tag + '-'.repeat(length)).slice(0, length)
}

export function createAgentActivityRedactor(homeUser: string): (value: unknown) => unknown {
  // WHY one placeholder per distinct name (review of #1353): a placeholder derived from the length
  // alone gave `startup` and `win-win` (both 7 characters) the same `project`, merging two private
  // projects into one in every regeneration. The index is assigned in walk order, which is
  // deterministic for the same input, so a re-run over the same corpus writes the same file.
  const projects = new Map<string, string>()
  const projectPlaceholder = (name: string): string => {
    let placeholder = projects.get(name)
    if (placeholder === undefined) {
      placeholder = padded(`p${projects.size.toString(36)}`, name.length)
      projects.set(name, placeholder)
    }
    return placeholder
  }

  // WHY each segment under a private project gets its own placeholder too (steering q74 regeneration):
  // x-filling the tail made `agent-code-audit-worktrees/commands-ui-shell` and `.../headless-packages`
  // (same length) the same string. As object KEYS (workActivity.touched is keyed by path) that merged
  // two entries into one — silent data loss the byte-length check caught. Same walk-order rule as
  // projects: deterministic for the same input.
  const segments = new Map<string, string>()
  const segmentPlaceholder = (segment: string): string => {
    if (segment === '') return segment
    let placeholder = segments.get(segment)
    if (placeholder === undefined) {
      const tag = `s${segments.size.toString(36)}`
      // A segment shorter than its tag is x-filled; the key-collision check in `redact` refuses the
      // file if that ever makes two keys equal.
      placeholder = tag.length > segment.length ? 'x'.repeat(segment.length) : (tag + 'x'.repeat(segment.length)).slice(0, segment.length)
      segments.set(segment, placeholder)
    }
    return placeholder
  }

  const redactPathText = (value: string): string => {
    let out = homeUser ? value.split(homeUser).join(homePlaceholder(homeUser)) : value
    // The name is the first path segment after `Development/` (or the whole dash-encoded tail of a
    // Claude projects dir, `-Development-<name>`). WHY the rest of the path goes too (review of
    // #1353): worktree names under a private repo (`win-win/.claude/worktrees/simplify`) are as
    // telling as branch names. Separators are kept so the path's shape survives. Agent Code paths
    // are the public repo and stay verbatim — the corpus is about this app.
    //
    // WHY the exact segment and not a prefix (review of #1353, steering q74): `startsWith` exempted
    // any private project whose name merely begins with `agent-code` (`agent-code-private`). Sibling
    // checkouts of the public repo named `agent-code-<task>` are redacted too as a result — over-
    // redaction costs nothing here, since the row model reads no path.
    out = out.replace(/(Development[-/])([^\s/"'`]+)((?:\/[^\s"'`]*)?)/g, (match, prefix: string, name: string, rest: string) =>
      name === PUBLIC_PROJECT ? match : prefix + projectPlaceholder(name) + rest.split('/').map(segmentPlaceholder).join('/'))
    return out
  }

  const redact = (value: unknown, key?: string): unknown => {
    if (Array.isArray(value)) return value.map(item => redact(item, key))
    if (value && typeof value === 'object') {
      const entries = Object.entries(value).map(([k, v]) => [redactPathText(k), redact(v, k)] as const)
      // Fail closed on a key collision: Object.fromEntries would silently keep only the last entry.
      if (new Set(entries.map(([k]) => k)).size !== entries.length) {
        throw new Error('redaction made two object keys equal; refusing to merge their entries')
      }
      return Object.fromEntries(entries)
    }
    if (typeof value === 'string') {
      return key !== undefined && TEXT_FIELDS.has(key) ? value.replace(/\S/g, 'x') : redactPathText(value)
    }
    return value
  }
  return value => redact(value)
}

/**
 * The `--home-user` a `--redact-from` run must be given, validated BEFORE anything is read or written.
 *
 * WHY required (steering q74): the pre-redaction fixture holds the RECORDER's home path. Defaulting to
 * the user running the script leaves that path intact on any other checkout, and writes it into the
 * tracked fixture. A name with a separator, or an empty one, cannot be a macOS short user name.
 */
export function requireHomeUser(argv: readonly string[]): string {
  const index = argv.indexOf('--home-user')
  const value = index === -1 ? undefined : argv[index + 1]
  if (value === undefined || value.trim() === '' || value.startsWith('--') || /[/\\\s]/.test(value)) {
    throw new Error('--redact-from needs --home-user <the recorder\'s short user name>; refusing to guess it')
  }
  return value
}

/**
 * Refuse INPUT whose home directories are not all the named recorder's.
 *
 * WHY on the input (review of #1353, round 3 a): the output guard below can only compare against
 * the placeholder, and a foreign user whose name happens to be spelled like the placeholder
 * (`/Users/fixture-` for an 8-character recorder) is indistinguishable from it after redaction.
 * Before redaction there is no such ambiguity: every home in the source must BE the recorder, so a
 * wrong `--home-user` is caught whatever the other user is called.
 */
export function assertHomesBelongTo(sourceJson: string, homeUser: string): void {
  const foreign = new Set<string>()
  for (const match of sourceJson.matchAll(/\/(?:Users|home)\/([^/"\s\\]+)/g)) {
    if (match[1] !== homeUser) foreign.add(match[1]!)
  }
  // Claude's dash-encoded dir (`-Users-<name>-Desktop-…`) has no delimiter after the name, so
  // `-Users-recorder-secret-Desktop-…` STARTS with `recorder-` although its user is
  // `recorder-secret` (steering q78). The encoding cannot be decoded, so it is accepted only when it
  // is unambiguous: the component right after the recorder must be a standard home folder, AND the
  // source must name that same folder canonically (`/Users/<recorder>/<folder>`, which has real
  // delimiters). The corpus's 38 dash homes are all `-Users-<recorder>-Desktop`, beside canonical
  // `/Users/<recorder>/Desktop` paths. Anything else refuses as ambiguous.
  let at = sourceJson.indexOf('-Users-')
  while (at !== -1) {
    const rest = sourceJson.slice(at + '-Users-'.length)
    const folder = rest.startsWith(`${homeUser}-`) ? rest.slice(homeUser.length + 1).split(/[-"\s/\\]/, 1)[0]! : ''
    const unambiguous = HOME_FOLDERS.has(folder) && sourceJson.includes(`/Users/${homeUser}/${folder}`)
    if (!unambiguous) foreign.add(`#${at}`)
    at = sourceJson.indexOf('-Users-', at + 1)
  }
  if (foreign.size > 0) throw new Error(`the source names a home directory other than --home-user (${foreign.size} occurrence${foreign.size === 1 ? '' : 's'}); not writing it`)
}

/**
 * Refuse output that still holds a home directory other than the placeholder, in ANY spelling.
 *
 * WHY a check on the RESULT as well: a wrong `--home-user` (or a live extraction on a machine whose
 * bundles came from another user) would pass any flag check; this runs on the redacted text right
 * before it is written.
 *
 * WHY every other spelling refuses outright (review of #1353, round 3 a): the pass rewrites only
 * the canonical `/Users/<name>` and Claude's dash-encoded `-Users-<name>-`. A home written any
 * other way — lowercase `/users/`, backslashes (`C:\Users\…`), JSON-escaped `\/`, percent-encoded
 * `%2F`, or `~name` — would pass through untouched, so its presence means the input has a shape this
 * policy does not handle, and the file must not be written. The committed corpus has none of these
 * (text fields, where `~` does occur, are x-filled before this runs).
 *
 * NOT covered, stated plainly: an identifier with no path around it in a field the policy does not
 * treat as text (`{ "user": "someone" }`). No pattern can recognise that. The corpus has no such
 * field; a regeneration from a DIFFERENT corpus needs its own full per-key audit, as this one had.
 */
export function assertNoForeignHome(redactedJson: string, homeUser: string): void {
  const allowed = homeUser === '' ? undefined : homePlaceholder(homeUser)
  const foreign = new Set<string>()
  // Any home-like segment after any separator spelling, case-insensitive. Only the exact canonical
  // `/Users/<placeholder>` (or `/home/<placeholder>`) passes; the slash path must BE the placeholder
  // (steering q76: a prefix of it is someone else).
  const home = /(\/|\\\\|\\\/|%2f)(users|home)(?:\/|\\\\|\\\/|%2f)+([^/\\%"\s]+)/gi
  for (const match of redactedJson.matchAll(home)) {
    const canonical = match[1] === '/' && (match[2] === 'Users' || match[2] === 'home') && match[0] === `/${match[2]}/${match[3]}`
    if (!canonical || match[3] !== allowed) foreign.add(`${match.index}`)
  }
  // Claude's dash-encoded projects dir, `-Users-<name>-Desktop-…`. A user name can itself contain
  // dashes (the placeholder does), so it cannot be parsed back out; instead every `-Users-` must be
  // followed by the whole placeholder and a dash. Anything else is foreign or ambiguous, and both
  // refuse. (The input check above is what catches a foreign name spelled like the placeholder.)
  let at = redactedJson.indexOf('-Users-')
  while (at !== -1) {
    if (allowed === undefined || !redactedJson.startsWith(`${allowed}-`, at + '-Users-'.length)) foreign.add(`-${at}`)
    at = redactedJson.indexOf('-Users-', at + 1)
  }
  for (const match of redactedJson.matchAll(/~[A-Za-z_][\w.-]*/g)) foreign.add(`~${match.index}`)
  // The count is of occurrences, and the message never repeats the name: it is printed to a
  // terminal and may be pasted into a PR.
  if (foreign.size > 0) throw new Error(`redacted output still names a home directory other than the placeholder (${foreign.size} occurrence${foreign.size === 1 ? '' : 's'}); not writing it`)
}
