import {
  defineRenderShape,
  defineRenderShapeCatalog,
} from '@renderer/rendering/evidence/defineRenderShape'

// Codex render-shape catalog (Phase 4, PR #555).
//
// SEEDED from the 48-bundle frozen corpus (19 codex bundles) — see the
// Claude catalog header for the seeding/grouping/disposition rules; they
// are identical here. Codex-specific notes baked into this corpus:
//   - TWO orchestration naming generations coexist (legacy spawn_agent/
//     wait_agent and current orchestration_*) — separate ids on purpose,
//     they are different wire vocabularies with different futures;
//   - the semantic plane uses function_call/message/reasoning kinds (not
//     Claude's text/tool_use/thinking) plus rare custom_tool_call and
//     web_search_call variants;
//   - NO unified-exec wrapper shapes appear in this corpus. When a modern
//     Codex CLI emits them they will land in the Unknown Shape Inbox —
//     that is the system working, not a gap in this file. Catalog them
//     from real sightings, never from PR #524's draft classifier.
export const CODEX_RENDER_SHAPES = defineRenderShapeCatalog('codex', {
  'codex.semantic.ai-workspace-attach-file.v1': defineRenderShape({
    id: 'codex.semantic.ai-workspace-attach-file.v1',
    provider: 'codex',
    fingerprints: ["fp1-46b11a08","fp1-e684a8c6"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (18 sightings); structural variants share this id.',
  }),
  'codex.semantic.ai-workspace-create.v1': defineRenderShape({
    id: 'codex.semantic.ai-workspace-create.v1',
    provider: 'codex',
    fingerprints: ["fp1-555245df"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (1 sightings); structural variants share this id.',
  }),
  'codex.semantic.ai-workspace-list-files.v1': defineRenderShape({
    id: 'codex.semantic.ai-workspace-list-files.v1',
    provider: 'codex',
    fingerprints: ["fp1-66af5be5"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (1 sightings); structural variants share this id.',
  }),
  'codex.semantic.apply-patch.v1': defineRenderShape({
    id: 'codex.semantic.apply-patch.v1',
    provider: 'codex',
    fingerprints: ["fp1-43e90a27","fp1-c31d4688"],
    eventTypes: ["custom_tool_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-06-18T11-37-47-852-e5236cbe.json","rendering-bundles/2026-06-23T08-41-35-901-d0bb555e.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'code-edit' },
    why: 'Seeded from the 48-bundle corpus (7 sightings); structural variants share this id.',
  }),
  'codex.semantic.exec.v1': defineRenderShape({
    id: 'codex.semantic.exec.v1',
    provider: 'codex',
    fingerprints: ["fp1-679797aa","fp1-9b9a69b3"],
    eventTypes: ["custom_tool_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (2 sightings); structural variants share this id.',
  }),
  'codex.semantic.exec-command.v1': defineRenderShape({
    id: 'codex.semantic.exec-command.v1',
    provider: 'codex',
    fingerprints: ["fp1-4c4186e6"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 48-bundle corpus (288 sightings); structural variants share this id.',
  }),
  'codex.semantic.list-agents.v1': defineRenderShape({
    id: 'codex.semantic.list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-57c4063b","fp1-5d5bc614","fp1-995423c3"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Codex list_agents has old and current schemas but no durable paired fixture; bounded structured JSON is truthful while a versioned table grammar remains unproven.' },
    why: 'Phase 7 intentionally keeps list_agents generic. The 2026-07-17 input-complete/prefix fingerprints are catalogued so upstream evolution is remembered without fabricating a schema-specific component.',
  }),
  'codex.semantic.message.v1': defineRenderShape({
    id: 'codex.semantic.message.v1',
    provider: 'codex',
    fingerprints: ["fp1-321e4161","fp1-469ca08d"],
    eventTypes: ["message"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T12-20-39-440-fd4bbb27.json","rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'prose' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (191 sightings); structural variants share this id.',
  }),
  'codex.semantic.orchestration-close-run.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-close-run.v1',
    provider: 'codex',
    fingerprints: ["fp1-6a00e11c","fp1-b2902050"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7 for the observed direct historical function-call grammar; current nested exec→MCP calls remain command rows and are not falsely merged into this operation.',
  }),
  'codex.semantic.orchestration-create-agent.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-create-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-04161150","fp1-77b08045","fp1-90024bf4","fp1-f7e03cb8"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T12-20-39-440-fd4bbb27.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: the historical bare function call is parsed as the source-controlled Agent Code protocol; strict result failure falls back visibly.',
  }),
  'codex.semantic.orchestration-list-agents.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-097bb801","fp1-6a999231","fp1-77d0c37d"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct historical Agent Code list calls share the owned bounded lifecycle view; arbitrary native list_agents remains a separate generic operation.',
  }),
  'codex.semantic.orchestration-read-agent.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-read-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-a3a3ffc7","fp1-cf9730dd"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct read-agent output is doubly bounded and lazy; current MCP-inside-exec output is only pretty-JSON formatted because cell correlation is not proven.',
  }),
  'codex.semantic.orchestration-read-run-outputs.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-read-run-outputs.v1',
    provider: 'codex',
    fingerprints: ["fp1-59ccc71b","fp1-98624d27"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: the owned multi-output contract caps agent rows and mounts message pages only after child disclosure.',
  }),
  'codex.semantic.orchestration-send-prompt.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-send-prompt.v1',
    provider: 'codex',
    fingerprints: ["fp1-31729a98"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct Agent Code send-prompt calls show target/status and preserve operation-specific delivery diagnostics in the raw protocol disclosure.',
  }),
  'codex.semantic.orchestration-wait-agents.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-wait-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-615dc5db","fp1-de751c05"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: wait results render every admitted agent summary before lazy per-agent output, including explicit timeout/truncation state.',
  }),
  'codex.semantic.reasoning.v1': defineRenderShape({
    id: 'codex.semantic.reasoning.v1',
    provider: 'codex',
    fingerprints: ["fp1-48584664","fp1-cdc8554d"],
    eventTypes: ["reasoning"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T12-20-39-440-fd4bbb27.json","rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'reasoning' },
    why: 'Seeded from the 48-bundle corpus (179 sightings); structural variants share this id.',
  }),
  'codex.semantic.spawn-agent.v1': defineRenderShape({
    id: 'codex.semantic.spawn-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-ac799d86","fp1-b1a3f043","fp1-ca116f72"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    why: 'GRADUATED Phase 7 with generation-aware input parsing: both frozen agent_type and current task_name calls share one bounded card, while unrecognized generations fall through and spawn acknowledgements remain visible.',
  }),
  'codex.semantic.wait-agent.v1': defineRenderShape({
    id: 'codex.semantic.wait-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-087966cb"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Legacy targeted status maps and current timeout/message responses are incompatible; the shared structured row preserves both without pretending one lifecycle model.' },
    why: 'Phase 7 intentionally keeps wait_agent generic until versioned invocation/result fixtures prove a stable provider component.',
  }),
  'codex.semantic.wait.v1': defineRenderShape({
    id: 'codex.semantic.wait.v1',
    provider: 'codex',
    fingerprints: ["fp1-cee28660","fp1-d3325ec0"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-17',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command-continuation' },
    why: 'TODO(command-continuation-evidence): current Codex `wait` resumes a yielded unified-exec cell; it is not the native wait_agent lifecycle and not Agent Code orchestration. These real complete/prefix fingerprints are catalogued now so Phase 7 does not accidentally claim them as collaboration, but a dedicated renderer must wait for paired continuation/result fixtures.',
  }),
  'codex.semantic.web-search-call.v1': defineRenderShape({
    id: 'codex.semantic.web-search-call.v1',
    provider: 'codex',
    fingerprints: ["fp1-2f07bc25","fp1-964ad542"],
    eventTypes: ["web_search_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    why: 'GRADUATED Phase 7: semantic search/open/find actions normalize into the same Codex web card as committed rollout. TODO(web-identity): ws_* versus synthetic committed ids lack a safe absorption bridge, so both remain independently visible when they overlap.',
  }),
  'codex.semantic.write-stdin.v1': defineRenderShape({
    id: 'codex.semantic.write-stdin.v1',
    provider: 'codex',
    fingerprints: ["fp1-d534209e"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 48-bundle corpus (38 sightings); structural variants share this id.',
  }),
  'codex.tool-result.custom-tool-call-output.v1': defineRenderShape({
    id: 'codex.tool-result.custom-tool-call-output.v1',
    provider: 'codex',
    fingerprints: ["fp1-8571cc95"],
    eventTypes: ["tool_result"],
    planes: ["committed-tool-result"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json","rendering-bundles/2026-05-21T09-12-59-519-e4f30416.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tool-result' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (25 sightings); structural variants share this id.',
  }),
  'codex.tool-result.patch-apply-end.v1': defineRenderShape({
    id: 'codex.tool-result.patch-apply-end.v1',
    provider: 'codex',
    fingerprints: ["fp1-0033a48e","fp1-1b549f52","fp1-9c456bea","fp1-d2336fb0","fp1-efb8be1e"],
    eventTypes: ["tool_result"],
    planes: ["committed-tool-result"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json","rendering-bundles/2026-05-21T09-12-59-519-e4f30416.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'code-edit' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (23 sightings); structural variants share this id.',
  }),
  'codex.tool-result.tool-result.v1': defineRenderShape({
    id: 'codex.tool-result.tool-result.v1',
    provider: 'codex',
    fingerprints: ["fp1-5b0abcb6"],
    eventTypes: ["tool_result"],
    planes: ["committed-tool-result"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tool-result' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (203 sightings); structural variants share this id.',
  }),
  'codex.tool-use.ai-workspace-attach-file.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-attach-file.v1',
    provider: 'codex',
    fingerprints: ["fp1-4d5ad8fb","fp1-579b18ba"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json","rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (36 sightings); structural variants share this id.',
  }),
  'codex.tool-use.ai-workspace-create.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-create.v1',
    provider: 'codex',
    fingerprints: ["fp1-57c7b414"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json","rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (2 sightings); structural variants share this id.',
  }),
  'codex.tool-use.ai-workspace-list-files.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-list-files.v1',
    provider: 'codex',
    fingerprints: ["fp1-6e9b4ecb"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json","rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (2 sightings); structural variants share this id.',
  }),
  'codex.tool-use.ai-workspace-open.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-open.v1',
    provider: 'codex',
    fingerprints: ["fp1-ad90a563"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (1 sightings); structural variants share this id.',
  }),
  'codex.tool-use.apply-patch.v1': defineRenderShape({
    id: 'codex.tool-use.apply-patch.v1',
    provider: 'codex',
    fingerprints: ["fp1-a55c7935"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json","rendering-bundles/2026-05-21T09-12-59-519-e4f30416.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    why: 'Seeded from the 48-bundle corpus (22 sightings); structural variants share this id. GRADUATED 2026-07-16: cut over to the code-edit protocol (adapter + CodeEditView); receipts must name this renderer or the sighting files as misrouted',
  }),
  'codex.tool-use.exec.v1': defineRenderShape({
    id: 'codex.tool-use.exec.v1',
    provider: 'codex',
    fingerprints: ["fp1-bb2ab36f"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (2 sightings); structural variants share this id.',
  }),
  'codex.tool-use.exec-command.v1': defineRenderShape({
    id: 'codex.tool-use.exec-command.v1',
    provider: 'codex',
    fingerprints: ["fp1-c24cb78f","fp1-e4175845"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    why: 'Seeded from the 48-bundle corpus (408 sightings); structural variants share this id. GRADUATED 2026-07-16: command protocol cutover (adapter + CommandView); receipts must name this renderer or sightings file as misrouted',
  }),
  'codex.tool-use.followup-task.v1': defineRenderShape({
    id: 'codex.tool-use.followup-task.v1',
    provider: 'codex',
    fingerprints: ["fp1-77cd1721"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'One invocation-only sighting does not prove result or lifecycle semantics; the bounded structured fallback preserves every field without inventing a task state.' },
    why: 'Phase 7 intentionally leaves followup_task generic. TODO(native-collaboration-evidence): graduate only after paired current-generation invocation/result fixtures establish durable task identity and delivery states.',
  }),
  'codex.tool-use.interrupt-agent.v1': defineRenderShape({
    id: 'codex.tool-use.interrupt-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-ebd10da6"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'One invocation-only sighting cannot distinguish requested, delivered, and already-closed outcomes; structured JSON is the honest rendering.' },
    why: 'Phase 7 intentionally leaves interrupt_agent generic. TODO(native-collaboration-evidence): add a provider row only when paired outputs prove stable target and terminal-state semantics.',
  }),
  'codex.tool-use.list-agents.v1': defineRenderShape({
    id: 'codex.tool-use.list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-e6c69b6a"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'The captured native list schema is too thin and current recordings already show a second generation; generic JSON preserves the open result contract.' },
    why: 'Phase 7 intentionally leaves list_agents generic rather than extrapolating a table from one committed invocation and incompatible live generations.',
  }),
  'codex.tool-use.orchestration-close-agent.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-close-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-e1dbbea9"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7 for the historical direct Agent Code protocol. The current MCP-inside-exec carrier remains a command row whose nested CallToolResult is pretty-formatted, because its cell provenance does not prove a direct orchestration call.',
  }),
  'codex.tool-use.orchestration-close-run.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-close-run.v1',
    provider: 'codex',
    fingerprints: ["fp1-26a0b16d","fp1-782a61d2"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T08-41-35-901-d0bb555e.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7 for direct historical Agent Code close-run calls; operation-specific run identifiers and failure diagnostics remain visible in the raw protocol disclosure.',
  }),
  'codex.tool-use.orchestration-create-agent.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-create-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-0f61d81c","fp1-4dd7966e","fp1-5e2248ee","fp1-a595182f","fp1-c4377ff9","fp1-ca218f41"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: the source-controlled Agent Code create contract gets a dedicated lifecycle card, while malformed or future generations decline to the bounded structured fallback.',
  }),
  'codex.tool-use.orchestration-list-agents.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-85a76d94","fp1-c000085f"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct Agent Code list results use a bounded owned-protocol table; native list_agents is deliberately separate and generic.',
  }),
  'codex.tool-use.orchestration-read-agent.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-read-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-481d078c"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct Agent Code read output is capped and lazy, with the exact result retained for forensic disclosure instead of being treated as an ordinary filesystem read.',
  }),
  'codex.tool-use.orchestration-read-run-outputs.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-read-run-outputs.v1',
    provider: 'codex',
    fingerprints: ["fp1-dc137904"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: the owned multi-agent output contract renders bounded summaries and lazy message pages; arbitrary MCP output never inherits this schema by name similarity.',
  }),
  'codex.tool-use.orchestration-send-prompt.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-send-prompt.v1',
    provider: 'codex',
    fingerprints: ["fp1-d5c55b7f"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-06-23T08-41-35-901-d0bb555e.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct Agent Code prompt delivery renders target and status while preserving delivery diagnostics and the exact raw protocol result.',
  }),
  'codex.tool-use.orchestration-wait-agents.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-wait-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-307fdc90","fp1-9eecebe7"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct Agent Code waits render all admitted agent summaries and lazy outputs, including explicit timeout/truncation state.',
  }),
  'codex.tool-use.send-message.v1': defineRenderShape({
    id: 'codex.tool-use.send-message.v1',
    provider: 'codex',
    fingerprints: ["fp1-e8529357"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'The single invocation sighting has no paired delivery result, so a success/failure badge would manufacture state that is not in evidence.' },
    why: 'Phase 7 intentionally leaves send_message generic. TODO(native-collaboration-evidence): graduate after paired fixtures prove stable recipient identity and delivery outcomes.',
  }),
  'codex.tool-use.spawn-agent.v1': defineRenderShape({
    id: 'codex.tool-use.spawn-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-5e28af9a","fp1-78dab7c7"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    why: 'GRADUATED Phase 7 with generation-aware parsing for both frozen agent_type and current task_name inputs. Unknown generations fall through to structured JSON, and spawn acknowledgements remain separately visible because result identity is not stable enough to absorb.',
  }),
  'codex.tool-use.update-plan.v1': defineRenderShape({
    id: 'codex.tool-use.update-plan.v1',
    provider: 'codex',
    fingerprints: ["fp1-1511e1b6"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tasks' },
    why: 'Seeded from the 48-bundle corpus (2 sightings); structural variants share this id.',
  }),
  'codex.tool-use.wait.v1': defineRenderShape({
    id: 'codex.tool-use.wait.v1',
    provider: 'codex',
    fingerprints: ["fp1-32f6d3bc"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command-continuation' },
    why: 'TODO(command-continuation-evidence): `wait` resumes a yielded unified-exec cell and must not be rendered as agent collaboration. Keep it planned for the command protocol until paired cell/result fixtures prove correlation and terminal states.',
  }),
  'codex.tool-use.wait-agent.v1': defineRenderShape({
    id: 'codex.tool-use.wait-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-032ae165","fp1-3db5716d"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Legacy per-agent status maps and current timeout/message responses are incompatible generations; structured JSON truthfully preserves both.' },
    why: 'Phase 7 intentionally leaves native wait_agent generic. TODO(native-collaboration-evidence): version the grammar only after paired current-generation fixtures expose stable identities and outcome states.',
  }),
  'codex.tool-use.web-search.v1': defineRenderShape({
    id: 'codex.tool-use.web-search.v1',
    provider: 'codex',
    fingerprints: ["fp1-0b98f9bb","fp1-183c6527"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    why: 'GRADUATED Phase 7: committed search/open/find actions share the bounded Codex web card. The row never invents citations or results because this wire shape contains action/status only.',
  }),
  'codex.tool-use.write-stdin.v1': defineRenderShape({
    id: 'codex.tool-use.write-stdin.v1',
    provider: 'codex',
    fingerprints: ["fp1-4751b52b"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    why: 'Seeded from the 48-bundle corpus (65 sightings); structural variants share this id. GRADUATED 2026-07-16: command protocol cutover (adapter + CommandView); receipts must name this renderer or sightings file as misrouted',
  }),})

export type CodexRenderShapeId = keyof typeof CODEX_RENDER_SHAPES
