import {
  defineRenderShape,
  defineRenderShapeCatalog,
} from '@renderer/rendering/evidence/defineRenderShape'

// Codex render-shape catalog (Phase 4, PR #555).
//
// SEEDED from the 48-bundle frozen corpus (19 codex bundles) — see the
// Claude catalog header for the seeding/grouping/disposition rules; they
// are identical here. Codex-specific notes baked into this corpus:
//   - TWO orchestration naming generations coexist (legacy spawn_agent/
//     wait_agent and current orchestration_*) — separate ids on purpose,
//     they are different wire vocabularies with different futures;
//   - the semantic plane uses function_call/message/reasoning kinds (not
//     Claude's text/tool_use/thinking) plus rare custom_tool_call and
//     web_search_call variants;
//   - the original 48-bundle seed predates unified exec, but reviewed
//     2026-07-16 semantic-prefix/final and committed fixtures now pin that
//     carrier below. Those retained sightings—not PR #524's draft
//     classifier—are the authority for its finite alternate routes.
// TODO(condition-shape-soak): trust-dialog and approval have source-controlled
// destinations but no retained condition-plane sightings yet. Their first real
// developer captures must remain unknown until reviewed fixtures pin the exact
// structures; do not synthesize fingerprints from the app mirror types.
export const CODEX_RENDER_SHAPES = defineRenderShapeCatalog('codex', {
  'codex.semantic.ai-workspace-attach-file.v1': defineRenderShape({
    id: 'codex.semantic.ai-workspace-attach-file.v1',
    provider: 'codex',
    fingerprints: ["fp2-46b11a08","fp2-e684a8c6"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.workspace' },
    why: 'GRADUATED Phase 8: the observed Codex bare built-in name is admitted by the source-controlled Agent Code AI Workspace schema, then rendered with explicit Agent Code MCP hierarchy and paired-result ownership.',
  }),
  'codex.semantic.ai-workspace-create.v1': defineRenderShape({
    id: 'codex.semantic.ai-workspace-create.v1',
    provider: 'codex',
    fingerprints: ["fp2-555245df"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.workspace' },
    why: 'GRADUATED Phase 8: complete create input reuses the owned Agent Code workspace protocol; malformed or incomplete arguments remain on the shared JSON fallback.',
  }),
  'codex.semantic.ai-workspace-list-files.v1': defineRenderShape({
    id: 'codex.semantic.ai-workspace-list-files.v1',
    provider: 'codex',
    fingerprints: ["fp2-66af5be5"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.workspace' },
    why: 'GRADUATED Phase 8: the source-controlled list-files operation owns its complete semantic input and validated ok-result, including lazy exact protocol evidence.',
  }),
  'codex.semantic.apply-patch.v1': defineRenderShape({
    id: 'codex.semantic.apply-patch.v1',
    provider: 'codex',
    fingerprints: ["fp2-43e90a27","fp2-c31d4688"],
    eventTypes: ["custom_tool_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-06-18T11-37-47-852-e5236cbe.json","rendering-bundles/2026-06-23T08-41-35-901-d0bb555e.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    alternateDispositions: [
      { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'A named apply_patch envelope without a parseable file header remains visible instead of inventing an empty edit.' },
    ],
    why: 'GRADUATED Phase 9: a named apply_patch call is specialized only after the bounded parser proves at least one file header. Incomplete prefixes and malformed grammar decline to the shared fallback, while admitted previews disclose truncation and preserve exact paged patch evidence.',
  }),
  'codex.semantic.compaction.v1': defineRenderShape({
    id: 'codex.semantic.compaction.v1',
    provider: 'codex',
    fingerprints: ["fp2-4016d91b","fp2-4a35edef"],
    eventTypes: ["compaction"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-17',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-shapes/codex/compaction/semantic-final.json"], prefixes: ["rendering-shapes/codex/compaction/semantic-prefix.json"] },
    disposition: { kind: 'specialized', rendererId: 'shared.compaction', protocolId: 'compaction.live' },
    why: 'GRADUATED Phase 10 from the captured structured Codex semantic item: prefix/final lifecycle paints compaction progress without screen parsing, and the later durable compacted rollout remains the replay source of truth for boundary + summary.',
  }),
  'codex.semantic.exec.v1': defineRenderShape({
    id: 'codex.semantic.exec.v1',
    provider: 'codex',
    fingerprints: ["fp2-679797aa","fp2-9b9a69b3"],
    eventTypes: ["custom_tool_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: {
      final: ["rendering-shapes/codex/exec/semantic-final.json"],
      prefixes: ["rendering-shapes/codex/exec/semantic-prefix.json"],
    },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'An unrecognized unified-exec script remains visible through the bounded structured fallback.' },
    alternateDispositions: [
      { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
      { kind: 'specialized', rendererId: 'shared.command', protocolId: 'command.git' },
    ],
    why: 'GRADUATED Phase 10: unified exec is admitted only after provider parsing proves an apply_patch call or embedded exec_command call. Arbitrary generated scripts stay generic. Complete transparent single-command bridges share native exec_command ownership, including the finite Git route. The bounded canonical Promise.all + numbered-forEach fan-out is also provider-owned because each result section is attributable and the exact grouped payload remains disclosed; ambiguous fan-outs and yielded envelopes retain separate result evidence. Direct text(output) carriers report an unproven exit as "unknown" rather than success.',
  }),
  'codex.semantic.exec-command.v1': defineRenderShape({
    id: 'codex.semantic.exec-command.v1',
    provider: 'codex',
    fingerprints: ["fp2-4c4186e6"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    alternateDispositions: [
      { kind: 'specialized', rendererId: 'shared.command', protocolId: 'command.git' },
      { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'A blank or malformed exec_command input remains visible through the bounded structured fallback.' },
    ],
    why: 'GRADUATED Phase 9: a complete native exec_command semantic block normally normalizes into Codex provider command rendering. The structural fingerprint deliberately ignores command text, so the finite Git interception and malformed-input fallback are declared explicitly instead of turning intended content-gated routing into a false misroute.',
  }),
  'codex.semantic.list-agents.v1': defineRenderShape({
    id: 'codex.semantic.list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp2-57c4063b","fp2-5d5bc614","fp2-995423c3"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Codex list_agents has old and current schemas but no durable paired fixture; bounded structured JSON is truthful while a versioned table grammar remains unproven.' },
    why: 'Phase 7 intentionally keeps list_agents generic. The 2026-07-17 input-complete/prefix fingerprints are catalogued so upstream evolution is remembered without fabricating a schema-specific component.',
  }),
  'codex.semantic.message.v1': defineRenderShape({
    id: 'codex.semantic.message.v1',
    provider: 'codex',
    fingerprints: ["fp2-321e4161","fp2-469ca08d"],
    eventTypes: ["message"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T12-20-39-440-fd4bbb27.json","rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Codex message items are provider-neutral prose painted by the shared semantic row after provider dispatch declines non-tool content.' },
    why: 'GRADUATED Phase 9: message items have one deterministic shared prose owner. Keeping them planned would allow a future accidental provider-tool route to pass the outcome audit unnoticed.',
  }),
  'codex.semantic.orchestration-close-run.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-close-run.v1',
    provider: 'codex',
    fingerprints: ["fp2-6a00e11c","fp2-b2902050"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7 for the observed direct historical function-call grammar; current nested exec→MCP calls remain command rows and are not falsely merged into this operation.',
  }),
  'codex.semantic.orchestration-create-agent.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-create-agent.v1',
    provider: 'codex',
    fingerprints: ["fp2-04161150","fp2-77b08045","fp2-90024bf4","fp2-f7e03cb8"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T12-20-39-440-fd4bbb27.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: the historical bare function call is parsed as the source-controlled Agent Code protocol; strict result failure falls back visibly.',
  }),
  'codex.semantic.orchestration-list-agents.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp2-097bb801","fp2-6a999231","fp2-77d0c37d"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct historical Agent Code list calls share the owned bounded lifecycle view; arbitrary native list_agents remains a separate generic operation.',
  }),
  'codex.semantic.orchestration-read-agent.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-read-agent.v1',
    provider: 'codex',
    fingerprints: ["fp2-a3a3ffc7","fp2-cf9730dd"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct read-agent output is doubly bounded and lazy; current MCP-inside-exec output is only pretty-JSON formatted because cell correlation is not proven.',
  }),
  'codex.semantic.orchestration-read-run-outputs.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-read-run-outputs.v1',
    provider: 'codex',
    fingerprints: ["fp2-59ccc71b","fp2-98624d27"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: the owned multi-output contract caps agent rows and mounts message pages only after child disclosure.',
  }),
  'codex.semantic.orchestration-send-prompt.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-send-prompt.v1',
    provider: 'codex',
    fingerprints: ["fp2-31729a98"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct Agent Code send-prompt calls show target/status and preserve operation-specific delivery diagnostics in the raw protocol disclosure.',
  }),
  'codex.semantic.orchestration-wait-agents.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-wait-agents.v1',
    provider: 'codex',
    fingerprints: ["fp2-615dc5db","fp2-de751c05"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: wait results render every admitted agent summary before lazy per-agent output, including explicit timeout/truncation state.',
  }),
  'codex.semantic.reasoning.v1': defineRenderShape({
    id: 'codex.semantic.reasoning.v1',
    provider: 'codex',
    fingerprints: ["fp2-48584664","fp2-cdc8554d"],
    eventTypes: ["reasoning"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T12-20-39-440-fd4bbb27.json","rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Visible reasoning text is painted by the provider-neutral semantic disclosure.' },
    alternateDispositions: [
      { kind: 'absorbed', ownerRendererId: 'semantic.blockrow', reason: 'Empty or encrypted reasoning is represented by the work indicator instead of a blank row.' },
    ],
    why: 'GRADUATED Phase 10 with a finite content split: visible reasoning uses the shared disclosure while empty/encrypted reasoning is explicitly absorbed by semantic.blockrow.',
  }),
  'codex.semantic.spawn-agent.v1': defineRenderShape({
    id: 'codex.semantic.spawn-agent.v1',
    provider: 'codex',
    fingerprints: ["fp2-ac799d86","fp2-b1a3f043","fp2-ca116f72"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    dispositionByLifecycle: { prefix: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Incomplete provider input remains visible through the bounded fallback until required fields close.' } },
    why: 'GRADUATED Phase 7 with generation-aware input parsing: both frozen agent_type and current task_name calls share one bounded card, while unrecognized generations fall through and spawn acknowledgements remain visible.',
  }),
  'codex.semantic.wait-agent.v1': defineRenderShape({
    id: 'codex.semantic.wait-agent.v1',
    provider: 'codex',
    fingerprints: ["fp2-087966cb"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Legacy targeted status maps and current timeout/message responses are incompatible; the shared structured row preserves both without pretending one lifecycle model.' },
    why: 'Phase 7 intentionally keeps wait_agent generic until versioned invocation/result fixtures prove a stable provider component.',
  }),
  'codex.semantic.wait.v1': defineRenderShape({
    id: 'codex.semantic.wait.v1',
    provider: 'codex',
    fingerprints: ["fp2-cee28660","fp2-d3325ec0"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-17',
      lastSeen: '2026-07-17',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'unsupported', reason: 'Codex wait continuation lacks stable paired cell/result evidence and therefore stays visibly structured by the generic tool row.' },
    why: 'Phase 10 intentionally does not guess that wait is collaboration or silently attach it to a command. TODO(command-continuation-evidence): promote only after paired yielded-cell fixtures prove correlation and terminal states.',
  }),
  'codex.semantic.web-search-call.v1': defineRenderShape({
    id: 'codex.semantic.web-search-call.v1',
    provider: 'codex',
    fingerprints: ["fp2-2f07bc25","fp2-964ad542"],
    eventTypes: ["web_search_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    why: 'GRADUATED Phase 7: semantic search/open/find actions normalize into the same Codex web card as committed rollout. TODO(web-identity): ws_* versus synthetic committed ids lack a safe absorption bridge, so both remain independently visible when they overlap.',
  }),
  'codex.semantic.write-stdin.v1': defineRenderShape({
    id: 'codex.semantic.write-stdin.v1',
    provider: 'codex',
    fingerprints: ["fp2-d534209e"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    alternateDispositions: [
      { kind: 'absorbed', ownerRendererId: 'codex.command-continuation', protocolId: 'command.continuation', reason: 'An empty transport poll is represented by the already-running command surface.' },
    ],
    why: 'GRADUATED Phase 10: non-empty input renders the Codex continuation row; an empty poll is an explicit operation-boundary absorption with a named command owner. React null is no longer an implicit routing protocol.',
  }),
  'codex.tool-result.custom-tool-call-output.v1': defineRenderShape({
    id: 'codex.tool-result.custom-tool-call-output.v1',
    provider: 'codex',
    fingerprints: ["fp2-8571cc95"],
    eventTypes: ["tool_result"],
    planes: ["committed-tool-result"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json","rendering-bundles/2026-05-21T09-12-59-519-e4f30416.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Unknown, uncorrelated, or arbitrary custom outputs remain visible through the shared structured result formatter.' },
    alternateDispositions: [
      { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
      { kind: 'absorbed', ownerRendererId: 'codex.rows.dispatch', reason: 'A validated paired provider card preserves the useful result evidence.' },
      { kind: 'absorbed', ownerRendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration', reason: 'The source-controlled Agent Code orchestration card preserves its validated result protocol.' },
      { kind: 'absorbed', ownerRendererId: 'codex.rows.dispatch', protocolId: 'agent-code.workspace', reason: 'The source-controlled Agent Code workspace card preserves its validated result protocol.' },
      { kind: 'absorbed', ownerRendererId: 'codex.command-continuation', protocolId: 'command.continuation', reason: 'An empty continuation acknowledgement belongs to the already-running command surface.' },
      { kind: 'absorbed', ownerRendererId: 'shared.command', protocolId: 'command.git', reason: 'The paired Git operation view preserves the bounded result evidence.' },
    ],
    why: 'GRADUATED Phase 10: correlation at the paired operation boundary determines the legal route. The open-world output envelope itself never grants a specialized or hidden claim.',
  }),
  'codex.tool-result.patch-apply-end.v1': defineRenderShape({
    id: 'codex.tool-result.patch-apply-end.v1',
    provider: 'codex',
    fingerprints: ["fp2-0033a48e","fp2-1b549f52","fp2-5ca46871","fp2-9c456bea","fp2-d2336fb0","fp2-efb8be1e"],
    eventTypes: ["tool_result"],
    planes: ["committed-tool-result"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json","rendering-bundles/2026-05-21T09-12-59-519-e4f30416.json"], prefixes: [] },
    disposition: { kind: 'absorbed', ownerRendererId: 'codex.rows.dispatch', reason: 'A successful patch receipt is already represented by the paired code-edit card.' },
    alternateDispositions: [
      { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
      { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'An uncorrelated or drifted patch result remains visible through the shared formatter.' },
    ],
    why: 'GRADUATED Phase 10: provider dispatch decides success absorption versus visible failure details before React. Missing correlation declines to the generic result instead of disappearing.',
  }),
  'codex.tool-result.tool-result.v1': defineRenderShape({
    id: 'codex.tool-result.tool-result.v1',
    provider: 'codex',
    fingerprints: ["fp2-5b0abcb6"],
    eventTypes: ["tool_result"],
    planes: ["committed-tool-result"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Unknown or uncorrelated results remain visibly formatted by the shared result fallback.' },
    alternateDispositions: [
      { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
      { kind: 'absorbed', ownerRendererId: 'codex.rows.dispatch', reason: 'A validated paired provider card preserves the useful result evidence.' },
      { kind: 'absorbed', ownerRendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration', reason: 'The source-controlled Agent Code orchestration card preserves its validated result protocol.' },
      { kind: 'absorbed', ownerRendererId: 'codex.rows.dispatch', protocolId: 'agent-code.workspace', reason: 'The source-controlled Agent Code workspace card preserves its validated result protocol.' },
      { kind: 'absorbed', ownerRendererId: 'codex.command-continuation', protocolId: 'command.continuation', reason: 'An empty continuation acknowledgement belongs to the already-running command surface.' },
      { kind: 'absorbed', ownerRendererId: 'shared.command', protocolId: 'command.git', reason: 'The paired Git operation view preserves the bounded result evidence.' },
    ],
    why: 'GRADUATED Phase 10: result ownership is derived from the correlated invocation. Every allowed specialized, absorbed, and generic route is finite and receipt-checked.',
  }),
  'codex.tool-use.ai-workspace-attach-file.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-attach-file.v1',
    provider: 'codex',
    fingerprints: ["fp2-4d5ad8fb","fp2-579b18ba"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json","rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.workspace' },
    why: 'GRADUATED Phase 8: the high-frequency attach-file shape now headlines the file/title under Agent Code MCP ownership instead of burying the path beneath generic parameters.',
  }),
  'codex.tool-use.ai-workspace-create.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-create.v1',
    provider: 'codex',
    fingerprints: ["fp2-57c7b414"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json","rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.workspace' },
    why: 'GRADUATED Phase 8: the committed create operation shares the exact owned protocol model with the semantic plane and absorbs only explicit boolean-ok results.',
  }),
  'codex.tool-use.ai-workspace-list-files.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-list-files.v1',
    provider: 'codex',
    fingerprints: ["fp2-6e9b4ecb"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json","rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.workspace' },
    why: 'GRADUATED Phase 8: committed list-files renders through the source-controlled workspace protocol with bounded/lazy result details.',
  }),
  'codex.tool-use.ai-workspace-open.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-open.v1',
    provider: 'codex',
    fingerprints: ["fp2-ad90a563"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.workspace' },
    why: 'GRADUATED Phase 8: the observed open operation now reads as an Agent Code UI action and retains its exact paired protocol evidence.',
  }),
  'codex.tool-use.apply-patch.v1': defineRenderShape({
    id: 'codex.tool-use.apply-patch.v1',
    provider: 'codex',
    fingerprints: ["fp2-a55c7935"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json","rendering-bundles/2026-05-21T09-12-59-519-e4f30416.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    alternateDispositions: [
      { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'A named apply_patch envelope without a parseable file header remains visible instead of inventing an empty edit.' },
    ],
    why: 'Seeded from the 48-bundle corpus (22 sightings); structural variants share this id. GRADUATED 2026-07-16: valid patches cut over to the code-edit protocol, while malformed grammar deliberately declines to the shared fallback because the content-insensitive fingerprint cannot distinguish those finite routes.',
  }),
  'codex.tool-use.exec.v1': defineRenderShape({
    id: 'codex.tool-use.exec.v1',
    provider: 'codex',
    fingerprints: ["fp2-bb2ab36f"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-shapes/codex/exec/committed.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'An unrecognized unified-exec script remains visible through the bounded structured fallback.' },
    alternateDispositions: [
      { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
      { kind: 'specialized', rendererId: 'shared.command', protocolId: 'command.git' },
    ],
    why: 'GRADUATED Phase 10: committed unified exec uses the same conservative provider admission as the semantic plane. Actual patch calls and embedded commands are provider-owned, while every unrecognized script remains visible. Transparent single-command bridges share native command operation ownership, including the finite Git route. The exact bounded Promise.all + numbered-forEach grammar owns and discloses its grouped output; ambiguous fan-outs and yielded envelopes retain separate result evidence. Unproven exits render as "unknown", never success.',
  }),
  'codex.tool-use.exec-command.v1': defineRenderShape({
    id: 'codex.tool-use.exec-command.v1',
    provider: 'codex',
    fingerprints: ["fp2-c24cb78f","fp2-e4175845"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    alternateDispositions: [
      { kind: 'specialized', rendererId: 'shared.command', protocolId: 'command.git' },
      { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'A blank or malformed exec_command input remains visible through the bounded structured fallback.' },
    ],
    why: 'Seeded from the 48-bundle corpus (408 sightings); structural variants share this id. GRADUATED 2026-07-16: valid commands use the command protocol, while Git interception and malformed-input fallback are explicit finite routes because command scalar contents do not participate in structural identity.',
  }),
  'codex.tool-use.followup-task.v1': defineRenderShape({
    id: 'codex.tool-use.followup-task.v1',
    provider: 'codex',
    fingerprints: ["fp2-77cd1721"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'One invocation-only sighting does not prove result or lifecycle semantics; the bounded structured fallback preserves every field without inventing a task state.' },
    why: 'Phase 7 intentionally leaves followup_task generic. TODO(native-collaboration-evidence): graduate only after paired current-generation invocation/result fixtures establish durable task identity and delivery states.',
  }),
  'codex.tool-use.interrupt-agent.v1': defineRenderShape({
    id: 'codex.tool-use.interrupt-agent.v1',
    provider: 'codex',
    fingerprints: ["fp2-ebd10da6"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'One invocation-only sighting cannot distinguish requested, delivered, and already-closed outcomes; structured JSON is the honest rendering.' },
    why: 'Phase 7 intentionally leaves interrupt_agent generic. TODO(native-collaboration-evidence): add a provider row only when paired outputs prove stable target and terminal-state semantics.',
  }),
  'codex.tool-use.list-agents.v1': defineRenderShape({
    id: 'codex.tool-use.list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp2-e6c69b6a"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'The captured native list schema is too thin and current recordings already show a second generation; generic JSON preserves the open result contract.' },
    why: 'Phase 7 intentionally leaves list_agents generic rather than extrapolating a table from one committed invocation and incompatible live generations.',
  }),
  'codex.tool-use.orchestration-close-agent.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-close-agent.v1',
    provider: 'codex',
    fingerprints: ["fp2-e1dbbea9"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7 for the historical direct Agent Code protocol. The current MCP-inside-exec carrier remains a command row whose nested CallToolResult is pretty-formatted, because its cell provenance does not prove a direct orchestration call.',
  }),
  'codex.tool-use.orchestration-close-run.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-close-run.v1',
    provider: 'codex',
    fingerprints: ["fp2-26a0b16d","fp2-782a61d2"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T08-41-35-901-d0bb555e.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7 for direct historical Agent Code close-run calls; operation-specific run identifiers and failure diagnostics remain visible in the raw protocol disclosure.',
  }),
  'codex.tool-use.orchestration-create-agent.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-create-agent.v1',
    provider: 'codex',
    fingerprints: ["fp2-0f61d81c","fp2-4dd7966e","fp2-5e2248ee","fp2-a595182f","fp2-c4377ff9","fp2-ca218f41"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: the source-controlled Agent Code create contract gets a dedicated lifecycle card, while malformed or future generations decline to the bounded structured fallback.',
  }),
  'codex.tool-use.orchestration-list-agents.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp2-85a76d94","fp2-c000085f"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct Agent Code list results use a bounded owned-protocol table; native list_agents is deliberately separate and generic.',
  }),
  'codex.tool-use.orchestration-read-agent.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-read-agent.v1',
    provider: 'codex',
    fingerprints: ["fp2-481d078c"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct Agent Code read output is capped and lazy, with the exact result retained for forensic disclosure instead of being treated as an ordinary filesystem read.',
  }),
  'codex.tool-use.orchestration-read-run-outputs.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-read-run-outputs.v1',
    provider: 'codex',
    fingerprints: ["fp2-dc137904"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: the owned multi-agent output contract renders bounded summaries and lazy message pages; arbitrary MCP output never inherits this schema by name similarity.',
  }),
  'codex.tool-use.orchestration-send-prompt.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-send-prompt.v1',
    provider: 'codex',
    fingerprints: ["fp2-d5c55b7f"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-06-23T08-41-35-901-d0bb555e.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct Agent Code prompt delivery renders target and status while preserving delivery diagnostics and the exact raw protocol result.',
  }),
  'codex.tool-use.orchestration-wait-agents.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-wait-agents.v1',
    provider: 'codex',
    fingerprints: ["fp2-307fdc90","fp2-9eecebe7"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch', protocolId: 'agent-code.orchestration' },
    why: 'GRADUATED Phase 7: direct Agent Code waits render all admitted agent summaries and lazy outputs, including explicit timeout/truncation state.',
  }),
  'codex.tool-use.send-message.v1': defineRenderShape({
    id: 'codex.tool-use.send-message.v1',
    provider: 'codex',
    fingerprints: ["fp2-e8529357"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'The single invocation sighting has no paired delivery result, so a success/failure badge would manufacture state that is not in evidence.' },
    why: 'Phase 7 intentionally leaves send_message generic. TODO(native-collaboration-evidence): graduate after paired fixtures prove stable recipient identity and delivery outcomes.',
  }),
  'codex.tool-use.spawn-agent.v1': defineRenderShape({
    id: 'codex.tool-use.spawn-agent.v1',
    provider: 'codex',
    fingerprints: ["fp2-5e28af9a","fp2-78dab7c7"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    why: 'GRADUATED Phase 7 with generation-aware parsing for both frozen agent_type and current task_name inputs. Unknown generations fall through to structured JSON, and spawn acknowledgements remain separately visible because result identity is not stable enough to absorb.',
  }),
  'codex.tool-use.update-plan.v1': defineRenderShape({
    id: 'codex.tool-use.update-plan.v1',
    provider: 'codex',
    fingerprints: ["fp2-1511e1b6"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    why: 'GRADUATED Phase 8: update_plan now renders a bounded checklist with exact whole-plan counts and absorbs only the frozen-corpus Plan updated acknowledgement.',
  }),
  'codex.tool-use.wait.v1': defineRenderShape({
    id: 'codex.tool-use.wait.v1',
    provider: 'codex',
    fingerprints: ["fp2-32f6d3bc"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'unsupported', reason: 'Codex wait continuation lacks stable paired cell/result evidence and therefore stays visibly structured by the generic tool row.' },
    why: 'Phase 10 explicitly keeps wait outside collaboration and outside silent command ownership. TODO(command-continuation-evidence): promote only when paired yielded-cell fixtures prove correlation and terminal states.',
  }),
  'codex.tool-use.wait-agent.v1': defineRenderShape({
    id: 'codex.tool-use.wait-agent.v1',
    provider: 'codex',
    fingerprints: ["fp2-032ae165","fp2-3db5716d"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'generic', rendererId: 'shared.generic-tool', reason: 'Legacy per-agent status maps and current timeout/message responses are incompatible generations; structured JSON truthfully preserves both.' },
    why: 'Phase 7 intentionally leaves native wait_agent generic. TODO(native-collaboration-evidence): version the grammar only after paired current-generation fixtures expose stable identities and outcome states.',
  }),
  'codex.tool-use.web-search.v1': defineRenderShape({
    id: 'codex.tool-use.web-search.v1',
    provider: 'codex',
    fingerprints: ["fp2-0b98f9bb","fp2-183c6527"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    why: 'GRADUATED Phase 7: committed search/open/find actions share the bounded Codex web card. The row never invents citations or results because this wire shape contains action/status only.',
  }),
  'codex.tool-use.write-stdin.v1': defineRenderShape({
    id: 'codex.tool-use.write-stdin.v1',
    provider: 'codex',
    fingerprints: ["fp2-4751b52b"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json"], prefixes: [] },
    disposition: { kind: 'specialized', rendererId: 'codex.rows.dispatch' },
    alternateDispositions: [
      { kind: 'absorbed', ownerRendererId: 'codex.command-continuation', protocolId: 'command.continuation', reason: 'An empty transport poll is represented by the already-running command surface.' },
    ],
    why: 'GRADUATED Phase 10: non-empty stdin is rendered by the Codex continuation row; an empty committed poll is explicitly absorbed by the running command owner instead of painting a blank stdin/result pair.',
  }),})

export type CodexRenderShapeId = keyof typeof CODEX_RENDER_SHAPES
