import {
  defineRenderShape,
  defineRenderShapeCatalog,
} from '@renderer/rendering/evidence/defineRenderShape'

// Codex render-shape catalog (Phase 4, PR #555).
//
// SEEDED from the 48-bundle frozen corpus (19 codex bundles) — see the
// Claude catalog header for the seeding/grouping/disposition rules; they
// are identical here. Codex-specific notes baked into this corpus:
//   - TWO orchestration naming generations coexist (legacy spawn_agent/
//     wait_agent and current orchestration_*) — separate ids on purpose,
//     they are different wire vocabularies with different futures;
//   - the semantic plane uses function_call/message/reasoning kinds (not
//     Claude's text/tool_use/thinking) plus rare custom_tool_call and
//     web_search_call variants;
//   - NO unified-exec wrapper shapes appear in this corpus. When a modern
//     Codex CLI emits them they will land in the Unknown Shape Inbox —
//     that is the system working, not a gap in this file. Catalog them
//     from real sightings, never from PR #524's draft classifier.
export const CODEX_RENDER_SHAPES = defineRenderShapeCatalog('codex', {
  'codex.semantic.ai-workspace-attach-file.v1': defineRenderShape({
    id: 'codex.semantic.ai-workspace-attach-file.v1',
    provider: 'codex',
    fingerprints: ["fp1-46b11a08","fp1-e684a8c6"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (18 sightings); structural variants share this id.',
  }),
  'codex.semantic.ai-workspace-create.v1': defineRenderShape({
    id: 'codex.semantic.ai-workspace-create.v1',
    provider: 'codex',
    fingerprints: ["fp1-555245df"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (1 sightings); structural variants share this id.',
  }),
  'codex.semantic.ai-workspace-list-files.v1': defineRenderShape({
    id: 'codex.semantic.ai-workspace-list-files.v1',
    provider: 'codex',
    fingerprints: ["fp1-66af5be5"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (1 sightings); structural variants share this id.',
  }),
  'codex.semantic.apply-patch.v1': defineRenderShape({
    id: 'codex.semantic.apply-patch.v1',
    provider: 'codex',
    fingerprints: ["fp1-43e90a27","fp1-c31d4688"],
    eventTypes: ["custom_tool_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-06-18T11-37-47-852-e5236cbe.json","rendering-bundles/2026-06-23T08-41-35-901-d0bb555e.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'code-edit' },
    why: 'Seeded from the 48-bundle corpus (7 sightings); structural variants share this id.',
  }),
  'codex.semantic.exec.v1': defineRenderShape({
    id: 'codex.semantic.exec.v1',
    provider: 'codex',
    fingerprints: ["fp1-679797aa","fp1-9b9a69b3"],
    eventTypes: ["custom_tool_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (2 sightings); structural variants share this id.',
  }),
  'codex.semantic.exec-command.v1': defineRenderShape({
    id: 'codex.semantic.exec-command.v1',
    provider: 'codex',
    fingerprints: ["fp1-4c4186e6"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 48-bundle corpus (288 sightings); structural variants share this id.',
  }),
  'codex.semantic.list-agents.v1': defineRenderShape({
    id: 'codex.semantic.list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-57c4063b"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'codex.semantic.message.v1': defineRenderShape({
    id: 'codex.semantic.message.v1',
    provider: 'codex',
    fingerprints: ["fp1-321e4161","fp1-469ca08d"],
    eventTypes: ["message"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T12-20-39-440-fd4bbb27.json","rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'prose' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (191 sightings); structural variants share this id.',
  }),
  'codex.semantic.orchestration-close-run.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-close-run.v1',
    provider: 'codex',
    fingerprints: ["fp1-6a00e11c","fp1-b2902050"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (6 sightings); structural variants share this id.',
  }),
  'codex.semantic.orchestration-create-agent.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-create-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-04161150","fp1-77b08045","fp1-90024bf4","fp1-f7e03cb8"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T12-20-39-440-fd4bbb27.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (18 sightings); structural variants share this id.',
  }),
  'codex.semantic.orchestration-list-agents.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-097bb801","fp1-6a999231","fp1-77d0c37d"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (7 sightings); structural variants share this id.',
  }),
  'codex.semantic.orchestration-read-agent.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-read-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-a3a3ffc7","fp1-cf9730dd"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'read-search' },
    why: 'Seeded from the 48-bundle corpus (35 sightings); structural variants share this id.',
  }),
  'codex.semantic.orchestration-read-run-outputs.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-read-run-outputs.v1',
    provider: 'codex',
    fingerprints: ["fp1-59ccc71b","fp1-98624d27"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'read-search' },
    why: 'Seeded from the 48-bundle corpus (2 sightings); structural variants share this id.',
  }),
  'codex.semantic.orchestration-send-prompt.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-send-prompt.v1',
    provider: 'codex',
    fingerprints: ["fp1-31729a98"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (10 sightings); structural variants share this id.',
  }),
  'codex.semantic.orchestration-wait-agents.v1': defineRenderShape({
    id: 'codex.semantic.orchestration-wait-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-615dc5db","fp1-de751c05"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (4 sightings); structural variants share this id.',
  }),
  'codex.semantic.reasoning.v1': defineRenderShape({
    id: 'codex.semantic.reasoning.v1',
    provider: 'codex',
    fingerprints: ["fp1-48584664","fp1-cdc8554d"],
    eventTypes: ["reasoning"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete","prefix"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T12-20-39-440-fd4bbb27.json","rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'reasoning' },
    why: 'Seeded from the 48-bundle corpus (179 sightings); structural variants share this id.',
  }),
  'codex.semantic.spawn-agent.v1': defineRenderShape({
    id: 'codex.semantic.spawn-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-b1a3f043"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (1 sightings); structural variants share this id.',
  }),
  'codex.semantic.wait-agent.v1': defineRenderShape({
    id: 'codex.semantic.wait-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-087966cb"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (1 sightings); structural variants share this id.',
  }),
  'codex.semantic.web-search-call.v1': defineRenderShape({
    id: 'codex.semantic.web-search-call.v1',
    provider: 'codex',
    fingerprints: ["fp1-2f07bc25","fp1-964ad542"],
    eventTypes: ["web_search_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'web' },
    why: 'Seeded from the 48-bundle corpus (4 sightings); structural variants share this id.',
  }),
  'codex.semantic.write-stdin.v1': defineRenderShape({
    id: 'codex.semantic.write-stdin.v1',
    provider: 'codex',
    fingerprints: ["fp1-d534209e"],
    eventTypes: ["function_call"],
    planes: ["semantic-tool"] as const,
    lifecycles: ["input-complete"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 48-bundle corpus (38 sightings); structural variants share this id.',
  }),
  'codex.tool-result.custom-tool-call-output.v1': defineRenderShape({
    id: 'codex.tool-result.custom-tool-call-output.v1',
    provider: 'codex',
    fingerprints: ["fp1-8571cc95"],
    eventTypes: ["tool_result"],
    planes: ["committed-tool-result"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json","rendering-bundles/2026-05-21T09-12-59-519-e4f30416.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tool-result' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (25 sightings); structural variants share this id.',
  }),
  'codex.tool-result.patch-apply-end.v1': defineRenderShape({
    id: 'codex.tool-result.patch-apply-end.v1',
    provider: 'codex',
    fingerprints: ["fp1-0033a48e","fp1-1b549f52","fp1-9c456bea","fp1-d2336fb0","fp1-efb8be1e"],
    eventTypes: ["tool_result"],
    planes: ["committed-tool-result"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json","rendering-bundles/2026-05-21T09-12-59-519-e4f30416.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'code-edit' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (23 sightings); structural variants share this id.',
  }),
  'codex.tool-result.tool-result.v1': defineRenderShape({
    id: 'codex.tool-result.tool-result.v1',
    provider: 'codex',
    fingerprints: ["fp1-5b0abcb6"],
    eventTypes: ["tool_result"],
    planes: ["committed-tool-result"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tool-result' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (203 sightings); structural variants share this id.',
  }),
  'codex.tool-use.ai-workspace-attach-file.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-attach-file.v1',
    provider: 'codex',
    fingerprints: ["fp1-4d5ad8fb","fp1-579b18ba"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json","rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (36 sightings); structural variants share this id.',
  }),
  'codex.tool-use.ai-workspace-create.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-create.v1',
    provider: 'codex',
    fingerprints: ["fp1-57c7b414"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json","rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (2 sightings); structural variants share this id.',
  }),
  'codex.tool-use.ai-workspace-list-files.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-list-files.v1',
    provider: 'codex',
    fingerprints: ["fp1-6e9b4ecb"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T12-55-50-798-7bab27ca.json","rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (2 sightings); structural variants share this id.',
  }),
  'codex.tool-use.ai-workspace-open.v1': defineRenderShape({
    id: 'codex.tool-use.ai-workspace-open.v1',
    provider: 'codex',
    fingerprints: ["fp1-ad90a563"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T14-52-00-547-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'structured-tool' },
    why: 'Seeded from the 48-bundle corpus (1 sightings); structural variants share this id.',
  }),
  'codex.tool-use.apply-patch.v1': defineRenderShape({
    id: 'codex.tool-use.apply-patch.v1',
    provider: 'codex',
    fingerprints: ["fp1-a55c7935"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json","rendering-bundles/2026-05-21T09-12-59-519-e4f30416.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'code-edit' },
    why: 'Seeded from the 48-bundle corpus (22 sightings); structural variants share this id.',
  }),
  'codex.tool-use.exec.v1': defineRenderShape({
    id: 'codex.tool-use.exec.v1',
    provider: 'codex',
    fingerprints: ["fp1-bb2ab36f"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (2 sightings); structural variants share this id.',
  }),
  'codex.tool-use.exec-command.v1': defineRenderShape({
    id: 'codex.tool-use.exec-command.v1',
    provider: 'codex',
    fingerprints: ["fp1-c24cb78f","fp1-e4175845"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 48-bundle corpus (408 sightings); structural variants share this id.',
  }),
  'codex.tool-use.followup-task.v1': defineRenderShape({
    id: 'codex.tool-use.followup-task.v1',
    provider: 'codex',
    fingerprints: ["fp1-77cd1721"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'codex.tool-use.interrupt-agent.v1': defineRenderShape({
    id: 'codex.tool-use.interrupt-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-ebd10da6"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'codex.tool-use.list-agents.v1': defineRenderShape({
    id: 'codex.tool-use.list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-e6c69b6a"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'codex.tool-use.orchestration-close-agent.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-close-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-e1dbbea9"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (4 sightings); structural variants share this id.',
  }),
  'codex.tool-use.orchestration-close-run.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-close-run.v1',
    provider: 'codex',
    fingerprints: ["fp1-26a0b16d","fp1-782a61d2"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T08-41-35-901-d0bb555e.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (10 sightings); structural variants share this id.',
  }),
  'codex.tool-use.orchestration-create-agent.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-create-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-0f61d81c","fp1-4dd7966e","fp1-5e2248ee","fp1-a595182f","fp1-c4377ff9","fp1-ca218f41"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (36 sightings); structural variants share this id.',
  }),
  'codex.tool-use.orchestration-list-agents.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-list-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-85a76d94","fp1-c000085f"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (8 sightings); structural variants share this id.',
  }),
  'codex.tool-use.orchestration-read-agent.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-read-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-481d078c"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json","rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'read-search' },
    why: 'Seeded from the 48-bundle corpus (36 sightings); structural variants share this id.',
  }),
  'codex.tool-use.orchestration-read-run-outputs.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-read-run-outputs.v1',
    provider: 'codex',
    fingerprints: ["fp1-dc137904"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-24T11-54-58-903-ad91e792.json","rendering-bundles/2026-06-24T19-13-07-337-75fb2add.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'read-search' },
    why: 'Seeded from the 48-bundle corpus (2 sightings); structural variants share this id.',
  }),
  'codex.tool-use.orchestration-send-prompt.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-send-prompt.v1',
    provider: 'codex',
    fingerprints: ["fp1-d5c55b7f"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-06-23T08-41-35-901-d0bb555e.json","rendering-bundles/2026-06-23T12-53-08-318-250d9f47.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (14 sightings); structural variants share this id.',
  }),
  'codex.tool-use.orchestration-wait-agents.v1': defineRenderShape({
    id: 'codex.tool-use.orchestration-wait-agents.v1',
    provider: 'codex',
    fingerprints: ["fp1-307fdc90","fp1-9eecebe7"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-09-04-906-7b859c43.json","rendering-bundles/2026-05-20T19-11-51-193-d4a44a16.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus (12 sightings); structural variants share this id.',
  }),
  'codex.tool-use.send-message.v1': defineRenderShape({
    id: 'codex.tool-use.send-message.v1',
    provider: 'codex',
    fingerprints: ["fp1-e8529357"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'codex.tool-use.spawn-agent.v1': defineRenderShape({
    id: 'codex.tool-use.spawn-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-5e28af9a","fp1-78dab7c7"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (7 sightings); structural variants share this id.',
  }),
  'codex.tool-use.update-plan.v1': defineRenderShape({
    id: 'codex.tool-use.update-plan.v1',
    provider: 'codex',
    fingerprints: ["fp1-1511e1b6"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'tasks' },
    why: 'Seeded from the 48-bundle corpus (2 sightings); structural variants share this id.',
  }),
  'codex.tool-use.wait.v1': defineRenderShape({
    id: 'codex.tool-use.wait.v1',
    provider: 'codex',
    fingerprints: ["fp1-32f6d3bc"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: [], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 2026-07-16 live capture soak (no bundle evidence yet) (1 sightings); structural variants share this id.',
  }),
  'codex.tool-use.wait-agent.v1': defineRenderShape({
    id: 'codex.tool-use.wait-agent.v1',
    provider: 'codex',
    fingerprints: ["fp1-032ae165","fp1-3db5716d"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'collaboration' },
    why: 'Seeded from the 48-bundle corpus + 2026-07-16 live capture (4 sightings); structural variants share this id.',
  }),
  'codex.tool-use.web-search.v1': defineRenderShape({
    id: 'codex.tool-use.web-search.v1',
    provider: 'codex',
    fingerprints: ["fp1-0b98f9bb","fp1-183c6527"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-06-18T11-12-28-535-21c515e9.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'web' },
    why: 'Seeded from the 48-bundle corpus (10 sightings); structural variants share this id.',
  }),
  'codex.tool-use.write-stdin.v1': defineRenderShape({
    id: 'codex.tool-use.write-stdin.v1',
    provider: 'codex',
    fingerprints: ["fp1-4751b52b"],
    eventTypes: ["tool_use"],
    planes: ["committed-tool-use"] as const,
    lifecycles: ["durable"] as const,
    observed: {
      providerVersions: [],
      models: [],
      firstSeen: '2026-07-16',
      lastSeen: '2026-07-16',
    },
    fixtures: { final: ["rendering-bundles/2026-05-20T14-00-04-079-b53fc4fe.json","rendering-bundles/2026-05-20T15-15-32-562-7b859c43.json","rendering-bundles/2026-05-20T18-43-47-377-f6d733f8.json"], prefixes: [] },
    disposition: { kind: 'planned', targetGrammar: 'command' },
    why: 'Seeded from the 48-bundle corpus (65 sightings); structural variants share this id.',
  }),})

export type CodexRenderShapeId = keyof typeof CODEX_RENDER_SHAPES
